### ISSUE TITLE
Python Socket.io client halts with message “Received unexpected packet of type 1”

### ISSUE THREAD

**Issue by iwctwbai** [miguelgrinberg/python-engineio#100]
my question is like this link, i don't know why,thanks

https://stackoverflow.com/questions/55099340/python-socket-io-client-halts-with-message-received-unexpected-packet-of-type-1

Thanks for answers

**Comment by miguelgrinberg** [comment]
Can you provide context? What code are you using, what error(s) do you get?

**Comment by iwctwbai** [comment]
My code is almost the same as the Stackoverflow link.
Error message only "Received unexpected packet of type 1" and socket.io (client) is disconnected.
Strangely, no callback was received when the connection was disconnected.
At this point, the program is running normally, but socket. IO is disconnected.
Thanks for answers！

**Comment by iwctwbai** [comment]
It's not easy to provide because it's commercial code.
The mistake happened accidentally. 
Today I have not been able to reproduce the problem. 
Under what circumstances will such an error (“Received unexpected packet of type 1”) be made?
Can higher CPU usage lead to problems?

**Comment by iwctwbai** [comment]
if I could reproduce the problem, I will contact you. thanks

**Comment by antrikshdua** [comment]
i have revived the same problem

**Comment by szero** [comment]
Just a hint towards possible issue. According to engine.io protocol, the `CLOSE` packet is expressed as `1`, which isn't handled in Client.py's `_receive_packet` method. In the code from SO from @iwctwbai , the emit event is issued without any de-bouncing. My guess would be that if you send packets to engine.IO server with full CPU speed, it triggers some sort of anti-flood measure and the server disconnects you.

**Comment by miguelgrinberg** [comment]
@szero thanks, I think I understand the problem now, which is actually simpler than I though. I just did not implement the CLOSE packet for the client, it is an unintentional omission on my part. I will add this to the client.

**Comment by aaronjswank** [comment]
Uncertain if related, but in addition to the "unexpected packet of type 1", I also see unexpected packet of type 5, 56  or type 35 and then on next message get a raise JSONDecodeError("Expecting value", s, err.value) from None.   Sometimes works just fine, and sometimes get the error when testing the exact same message.   (using the python socketio async client)

**Comment by miguelgrinberg** [comment]
@aaronjswank what server are you using?

**Comment by aaronjswank** [comment]
I am using flask_socketio with eventlet as main server

**Comment by miguelgrinberg** [comment]
@aaronjswank it's a different issue that I wasn't aware of. Easy to reproduce? Maybe you can share some code so that I can see the issue here?

**Comment by aaronjswank** [comment]
It's easy to reproduce.  Let me see if I can trim the code down to something easy to share.

**Comment by aaronjswank** [comment]
Here is a quick extraction of code.   Simple one word messages rarely cause issues.  Multiple word sentences sometimes generate "received unexpected packet of type" errors.

https://github.com/aaronjswank/flask-socketio-python-client
