### ISSUE TITLE
Lots of WARNING logs

### ISSUE THREAD

**Issue by bachya** [miguelgrinberg/python-engineio#102]
Submitting on behalf of an issue discovered by the use of this library (and `python-socketio`) in [Home Assistant](https://github.com/home-assistant/home-assistant): https://github.com/home-assistant/home-assistant/issues/22295

We are receiving lots of these `WARNING`-level entries in our logs:

```
2019-03-22 12:07:38 WARNING (MainThread) [engineio.client] Read loop: WebSocket connection was closed, aborting
2019-03-22 12:07:38 WARNING (MainThread) [engineio.client] Write loop: WebSocket connection was closed, aborting
```

From my understanding (and [previous work with you](https://github.com/miguelgrinberg/python-socketio/issues/249)), I expect these occur when the client gets unexpectedly disconnected from the socket. Since the client automatically reconnects, there isn't any user-facing impact – they merely see large amounts of "nothing to worry about" logs.

Would you consider taking this to `INFO` level if a reconnect is successful? Open to other alternatives and thoughts.

**Comment by miguelgrinberg** [comment]
I'm okay with downgrading these messages to INFO, that seems reasonable. Do you wan to create a PR for this change?

**Comment by bachya** [comment]
Will do! Is there other logging – here or in `python-socketio` – that you feel falls under the same banner (i.e., because the end-result was taken care of, `WARNING` is too steep)?
