### ISSUE TITLE
This implementation will not allow HTTPS connections.

### ISSUE THREAD

**Issue by ashishk88** [miguelgrinberg/python-engineio#111]
https://github.com/miguelgrinberg/python-engineio/blob/261fd67103cb5d9a44369415748e66fdf62de6fb/engineio/client.py#L442

For HTTPS connection, the verify parameter has to be passed with CA certificate.

**Comment by miguelgrinberg** [comment]
From the requests documentation:

> This list of trusted CAs can also be specified through the REQUESTS_CA_BUNDLE environment variable.

Any reason why that would not work?
