### ISSUE TITLE
3.8.0 python2 support?

### ISSUE THREAD

**Issue by datadidit** [miguelgrinberg/python-engineio#115]
Ran into this issue via Flask SocketIO bringing in the latest version of this middleware. Haven't dug deeper but my guess is latest version doesn't work with python2?

![Screen Shot 2019-06-03 at 4 12 24 PM](https://user-images.githubusercontent.com/10933169/58831765-68ae4080-861b-11e9-8eba-e58db3c360e4.png)

**Comment by miguelgrinberg** [comment]
The example application works fine for me. Are you doing anything unusual with the middleware?

**Comment by datadidit** [comment]
It works locally but when we ran our build in Travis this stacktrace pops up. I can try to reproduce in a public repo at some point. 

Adding 3.7.0 to our requirements fixed the build in Travis. Which is our patch for now.

**Comment by miguelgrinberg** [comment]
@datadidit this is failing during a request that you sent out through the Flask test client. Can you show me the code in the failing test and which line is it causing this error?

**Comment by datadidit** [comment]
@miguelgrinberg Here's an example of one of our tests that started failing:

```python
# App Creation
APP = Flask(__name__, instance_relative_config=True)
load_app_config(APP)
QI = QueryInspect(APP)
Compress(APP)
DB = SQLAlchemy(APP)
SOCKETIO = SocketIO(APP, async_mode=None)
BCRYPT = Bcrypt(APP)

# Test Code
client = APP.test_client()
response = client.get('<url>', headers=AUTH)
```

Thanks in advance for the help.

**Comment by miguelgrinberg** [comment]
@datadidit are you actually sending the URL `<url>` to the test client, or are you sending something that is valid? The error suggests the URL that you sent to the test client is invalid.

**Comment by datadidit** [comment]
@miguelgrinberg it's something that's valid.

**Comment by miguelgrinberg** [comment]
I need to see the exact route that you are calling when this failure occurs, not just a random example route. Look in the stack trace of your test to locate the actual one please.
