### ISSUE TITLE
Understanding the spawning of threads when using long-polling

### ISSUE THREAD

**Issue by ragymorkos** [miguelgrinberg/python-engineio#116]
I'm trying to understand how the Engine.IO protocol, specifically this Python server implementation, works when it comes to threading with long-polling. My goal is to find out in what cases the spawning of threads occurs. This is for understanding/learning/research purposes.

I am currently using Flask-SocketIO for my server, but most of the tracing I did points to the Engine.IO layer, so I thought it would be most suitable to open the issue here, especially since this is a lower-level question and Engine.IO is the lowest level of the Socket.IO protocol.

I currently have some JSON data I send back and forth between the server using long-polling (I explicitly set `async_mode = "threading"` when instantiating the Flask-SocketIO object in my application).

My code only has one active thread when first running the server, which makes sense, given that there's no need for other threads when no clients are connecting.

However, things start to make less sense when the server receives the first message from the client. When I log the number of threads and what function is running inside them, there seems to be 4 running:

1. `/usr/lib/python2.7/SocketServer.py | _eintr_retry | 146 | MainThread`
2. `/usr/lib/python2.7/threading.py | wait | 309 | Thread-3`
3. `<my_path_to_file> | <my_function_name> | <my_lineNo> | Thread-4`
4. `venv/lib/python2.7/site-packages/engineio/server.py | sleep | 422 | Thread-2`

The format above is:

`<path_to_file> | <function_name> | <lineNo> | <ThreadName>`

The third thread in the lines above belongs to my code, where I log the info. I placed the log call inside my handler function for the message the client sends.

The following logging lines are taken from the handler function on the subsequent message from the client:

1. `/usr/lib/python2.7/SocketServer.py | _eintr_retry | 146 | MainThread`
2. `/usr/lib/python2.7/threading.py | wait | 309 | Thread-5`
3. `<my_path_to_file> | <my_function_name> | <my_lineNo> | Thread-6`
4. `venv/lib/python2.7/site-packages/engineio/server.py | sleep | 422 | Thread-2`

And it keeps going on in this sequence for the remaining messages. So the threads where the functions `_eintr_retry` in the MainThread (first line) and `sleep` in Thread-2 (fourth line) are running seem to stay alive as the client keeps sending messages. The functions `wait` in the threading library (second line) and the code running in my handler function (line 3) seem to run in a new thread on each new message from the client.

I have a couple of questions regarding my logs:

1. Why are there 4 threads? I understand one has to be for listening for new connections / messages, and one has to be for handling the current connection (what runs in the handler function). But what is the use of the other two threads?

2. Following from my question above, what is really happening in all of those 3 threads (lines 1, 2, and 4)? The functions `_eintr_retry`, `wait`, and `sleep` are cryptic to me, so I was wondering if you could shed some light on what is actually happening there.

If you could provide me with a sample flow of events, and when each thread is spawned, I would greatly appreciate it.

P.S: I haven't taken the pings and pongs that get sent into account, but since these get sent only every 60 seconds (the default setting), then I assume they don't relate to the threads seen above in my log.

Thanks in advance, Miguel!

**Comment by miguelgrinberg** [comment]
Thread 1 in your list is the listener from the Flask development server. Basically the code that runs when you call `app.run()` or `socketio.run()`.

Thread 3 is the handler for your code. The Flask dev server is multithreaded, it spawns a new thread each time it dispatches a request to a handler. The Engine.IO server is also multithreaded. Not sure if your function is a Flask handler or an Engine.IO handler, but either way, each time a handler is invoked a new thread will be created for it.

Thread 2 and 4 are harder to analyze, you need to obtain a full stack trace. I'm pretty sure that thread 4 is the Engine.IO service task, which ensures orphaned sockets are disposed. I'm not sure what thread 2 is, if you get the full stack trace it should be pretty easy to determine.

**Comment by ragymorkos** [comment]
Thanks for your prompt response, Miguel! You are right; thread 4 was indeed responsible for cleanup of inactive/disconnected sessions. I've double checked that is the case by passing `monitor_clients = False` to the Flask-SocketIO constructor, and I am now seeing only 3 threads in my trace.

Regarding thread 2, I've done a full stack trace and it seems to be the thread in which the long-polling occurs. The trace goes something along the following lines:

`poll()` (Engine.IO/socket.py) --> `get()` (Queue.py in native Python library) --> `wait()` (threading.py in native Python library)

Since long-polling is an asynchronous operation whereby the server waits for data to be available before sending it to the client, it makes sense that this would happen in its separate thread.

Thread 3 is for an Engine.IO handler; I'm currently not making use of the Flask handlers, though it is useful to know I should expect more threads when I do make use of them.

Let me know if my understanding isn't correct regarding any of this. Otherwise, feel free to close this issue. Thanks a lot!

**Comment by miguelgrinberg** [comment]
@ragymorkos okay, yes, that makes perfect sense, should have realized that. That is the POST request that the Socket.IO client sends. It's handler, like all HTTP handlers is also allocated a thread.

I think that covers everything, right? If you have any other questions feel free to reopen the ticket.
