### ISSUE TITLE
Question regarding purpose of POST requests

### ISSUE THREAD

**Issue by ragymorkos** [miguelgrinberg/python-engineio#121]
I'm continuing my tinkering started in #116, and I've ran into something I can't find an explanation of myself. I'm still using HTTP and regular threads. For reference, my socket.io-client application simply sends an array of integers to the server.

Right before the return statement of `handle_request` in server.py, I print out the request method, the response, and the thread where `handle_request` is running in. This is a sample of the pattern I get:

```
GET
Thread-1
98:0{"pingInterval":25000,"pingTimeout":60000,"upgrades":[],"sid":"556b5c1d50544380884e5cc7e662788b"}2:40

POST
Thread-3
OK

GET
Thread-2
230:430[<My_response>]

POST
Thread-5
OK

GET
Thread-4
231:431[<My_response>]

POST
Thread-7
OK

GET
Thread-6
273:432[<My_response>]
```

I have two questions:

1) What is the purpose of the POST messages that get received above?

2) Why does the thread handling the GET request get created before the one handling the POST request, yet printed out after it?

Thanks in advance, Miguel!

**Comment by miguelgrinberg** [comment]
The GET + POST dance is called long-polling. Basically you need to emulate a bi-directional pipe on which either the client or the server can send data to the other side without any delay. So it works like this:

- If the client needs to send data, it sends it in a POST request.
- The server cannot initiate an HTTP exchange to send data to the client, so the client sends a GET request and the server sits on it until it has data to send in the response or it times out, whichever happens first. If the GET request times out, it returns an empty response, and then the client sends another GET request for another polling cycle.

Hope this helps.

**Comment by ragymorkos** [comment]
Thanks for the response, Miguel! If I understand correctly, this means that the client sends the array of integers (my application's input) in a POST request, and gets the OK response seen above. Then, the client sends the GET request to obtain the server's _actual_ response, with the server sitting on the request until the response is ready and then sends it over. This makes sense, since in the example above, every POST request gets sent before a GET request.

However, I'm still confused as to why the client's POST request doesn't just receive back a response from the server, instead of having the GET request being sent _just_ to get the response back corresponding to the POST request. In other words, can't the POST request just receive the response (instead of the simple "OK" above) and the client won't have to send the GET request that follows altogether?

**Comment by miguelgrinberg** [comment]
> However, I'm still confused as to why the client's POST request doesn't just receive back a response from the server

This is actually how HTTP works. If this is how you need things to work, then Socket.IO is not giving you any benefit over HTTP. The idea with Socket.IO is that the server can initiate an exchange, which is not possible with HTTP.

**Comment by ragymorkos** [comment]
I get that this is how HTTP works, but I still don't get why in my application's specific case, long-polling doesn't behave that way.

I currently have no event listeners on the client side that expect any unsolicited messages from the server. So the client never actually has any reason to poll the server using the GET request for anything. Any data received from the server is a response to an array of integers sent by the client in the POST request.

In light of my specific setup, why doesn't long-polling just behave like regular HTTP and have the response to the POST request be sent directly as a response instead of the "OK" response that is instead received? This would render the GET request used for the long-polling unnecessary in my case since I don't have any event handlers installed on the client side.

**Comment by miguelgrinberg** [comment]
> long-polling doesn't behave that way.

Long-polling behaves always in the same way. It's not affected by what you application does.

> I currently have no event listeners on the client side that expect any unsolicited messages from the server.

The long-polling cycle is done regardless of what event handlers your application has registered for.

> Any data received from the server is a response to an array of integers sent by the client in the POST request.

You are not "responding" here. You are sending a completely separate event that is initiated by the server. Events are handled asynchronously, by the time you send your response, the POST request has ended and the client received its OK response.

> In light of my specific setup, why doesn't long-polling just behave like regular HTTP 

Then it wouldn't be long-polling, it would be HTTP. Long-polling is a very specific technique, that's what the Socket.IO protocol implements. You can come up with all sorts of derivative protocols that serve your application better, but then you are on your own, you can't use Socket.IO.

**Comment by ragymorkos** [comment]
> The long-polling cycle is done regardless of what event handlers your application has registered for.

This is the part I was missing. I actually thought all this time that if there weren't any event handlers installed on the client, that the server-client communication would look like regular HTTP.

One final thing: do you know of any resource(s) (books or others) that discuss networking protocols in great detail? I have read a lot about long-polling on the web, blogs, etc. but never saw mention of something like the dedicated long-polling cycle. So a resource that goes in-depth on the implementations and the little details rather than just scratch the surface seems to be needed. Feel free to close this issue if you can't think of any resources for this. Thanks a ton, Miguel!

**Comment by miguelgrinberg** [comment]
I don't know of any books that cover long-polling. I wouldn't even call it a protocol, and less a network protocol. It is just an abuse of the HTTP protocol that some clever person came up with to implement a server push solution.
