### ISSUE TITLE
disconnect() engineio.client has unexpected message on screen

### ISSUE THREAD

**Issue by lgprobert** [miguelgrinberg/python-engineio#125]
The `disconnect()` function of `client` module in `python-engineio==3.8.2` has following print statement  that produces unexpected screen output when `disconnect()` is called:
```python
# client.py 
def disconnect(self, abort=False):
      print('***', self.state)
      ...
```
This message is directly propagated to application's console and I can't find a way to filter it out. It would be nice to remove it if it is not necessary. 

Thanks

**Comment by miguelgrinberg** [comment]
Sorry about that! Fixed in release `3.8.2.post1`.
