### ISSUE TITLE
Wrong build on pypi

### ISSUE THREAD

**Issue by PierrePaul** [miguelgrinberg/python-engineio#13]
The 0.8.6 build is different than the one tagged here : 
https://pypi.python.org/packages/source/p/python-engineio/python-engineio-0.8.6.tar.gz#md5=622bc4e73289a84e984faacc2f35c4e4

For example, async_gevent.py has multiple print('send/receive') statement not found in the tagged release on github.

**Comment by PierrePaul** [comment]
Running this fixes the problem in the meantime:
```bash
pip uninstall python-engineio
pip install git+https://github.com/miguelgrinberg/python-engineio.git#0.8.6
```

**Comment by miguelgrinberg** [comment]
Yeah, it appears I left some debugging when I submitted v0.8.6. I have made a new release 0.8.7 to clear things up. Thanks!

**Comment by PierrePaul** [comment]
You're awesome. Thank you!

**Comment by miguelgrinberg** [comment]
I would be awesome if I didn't leave debugging code in my builds, but thanks anyway. :)

**Comment by PierrePaul** [comment]
Considering all the work you've been doing, you've got a lot more leeway :)
