### ISSUE TITLE
Server Pong Frame doesn't match Ping Frame "Application data"

### ISSUE THREAD

**Issue by NoevilMe** [miguelgrinberg/python-engineio#130]
Hi, I reported an issue https://github.com/miguelgrinberg/python-socketio/issues/310. 
aaugustin found the Pong Frame data doesn't match the Ping Frame.

log：
```
2019-06-26 18:40:59,172 DEBUG protocol.py:898 client > Frame(fin=True, opcode=9, data=b'\xd8\xceh\x1f', rsv1=False, rsv2=False, rsv3=False)
2019-06-26 18:40:59,173 DEBUG protocol.py:886 client < Frame(fin=True, opcode=10, data=b'\xbaq.C\x1e\x00', rsv1=False, rsv2=False, rsv3=False)
2019-06-26 18:40:59,173 DEBUG protocol.py:867 client - received unsolicited pong: ba712e431e00
```

As far as I can tell, the issue is a non-compliant server which breaks https://tools.ietf.org/html/rfc6455#section-5.5.3.

 websockets 7.0+ will check the pong packet and it's recognized as timeout connection.

**Comment by miguelgrinberg** [comment]
This is all internal websocket protocol, not something this package has visibility into. What is the server that you are using?

**Comment by NoevilMe** [comment]
At first, I used socketio.AsyncClient() and flask-socketio server/socketio.Server(). It appeared.
Now, I find engineio.Server() and engineio.AsyncClient() have the same issue.

**Comment by miguelgrinberg** [comment]
@NoevilMe the question is what Websocket server are you using. Eventlet, gevent-websocket or uwsgi? That's where the problem is, not in this package.

**Comment by NoevilMe** [comment]
OK, I used eventlet. 

sample code: 
```
import engineio
import eventlet

eio = engineio.Server()
app = engineio.WSGIApp(eio)

@eio.on('connect')
def connect(sid, environ):
    print("connect ", sid)

@eio.on('message')
def message(sid, data):
    print("message ", data)
    eio.send(sid, 'reply')

@eio.on('disconnect')
def disconnect(sid):
    print('disconnect ', sid)

if __name__ == '__main__':
    eventlet.wsgi.server(eventlet.listen(('', 5000)), app)
```
Thanks

**Comment by NoevilMe** [comment]
I tried gevent-websocket server. That works well.   Thanks @miguelgrinberg for your explantion.
