### ISSUE TITLE
Client throws "TypeError 'Handlers' object not callable" if no original SIGINT handler

### ISSUE THREAD

**Issue by batesmotel34** [miguelgrinberg/python-engineio#139]
Found this exception when interrupting a sleep in a background process with SIGINT.  The signal_handler function should properly handle the case where original_signal_handler is nil or otherwise not callable.

**Comment by miguelgrinberg** [comment]
Yeah, good catch. I'll take care of it, unless you want to give it a try yourself and submit a PR?

**Comment by batesmotel34** [comment]
PR submitted.

**Comment by miguelgrinberg** [comment]
Addressed by #143. Closing.
