### ISSUE TITLE
Can not using 'msgpack' replace 'json'

### ISSUE THREAD

**Issue by LokiWager** [miguelgrinberg/python-engineio#150]
When I create Server object using `Server(json=msgpack)`, there are something wrong. Because msgpack dose not have separators paramters. 

in '/engineio/packet.py' line 48 `self.json.dumps(self.data, separators=(',', ':'))`

**Comment by miguelgrinberg** [comment]
First, the requirement is that your alternative json library is compatible with Python's. Second, Socket.IO requires JSON, you cannot replace it with a binary serialization format at the protocol level. You can send binary packets if you like, but you need to do your own encoding and decoding.
