### ISSUE TITLE
Incorrect pypi wheel which might destroy other packages

### ISSUE THREAD

**Issue by chrisoro** [miguelgrinberg/python-engineio#151]
When installing your released pypi packaged it will install the following taken from RECORD:

> engineio/__init__.py,sha256=GHBc2j_q1XPQ91avoCUXPBxHk2qVAdym9A0dabkYlvI,787
> engineio/__pycache__/__init__.cpython-37.pyc,,
> engineio/__pycache__/async_aiohttp.cpython-37.pyc,,
> engineio/__pycache__/async_asgi.cpython-37.pyc,,
> engineio/__pycache__/async_eventlet.cpython-37.pyc,,
> engineio/__pycache__/async_gevent.cpython-37.pyc,,
> engineio/__pycache__/async_gevent_uwsgi.cpython-37.pyc,,
> engineio/__pycache__/async_sanic.cpython-37.pyc,,
> engineio/__pycache__/async_threading.cpython-37.pyc,,
> engineio/__pycache__/async_tornado.cpython-37.pyc,,
> engineio/__pycache__/asyncio_client.cpython-37.pyc,,
> engineio/__pycache__/asyncio_server.cpython-37.pyc,,
> engineio/__pycache__/asyncio_socket.cpython-37.pyc,,
> engineio/__pycache__/client.cpython-37.pyc,,
> engineio/__pycache__/exceptions.cpython-37.pyc,,
> engineio/__pycache__/middleware.cpython-37.pyc,,
> engineio/__pycache__/packet.cpython-37.pyc,,
> engineio/__pycache__/payload.cpython-37.pyc,,
> engineio/__pycache__/server.cpython-37.pyc,,
> engineio/__pycache__/socket.cpython-37.pyc,,
> engineio/__pycache__/static_files.cpython-37.pyc,,
> engineio/async_aiohttp.py,sha256=6s9YFxW8ncAAlHJfvzaPTf0oGBJ61N5vzAJ2mrEwh2k,3824
> engineio/async_asgi.py,sha256=jvR_j3xToXJdOrU10VkwTRbBbltxSEdbZlTc2blvvdw,8426
> engineio/async_drivers/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
> engineio/async_drivers/__pycache__/__init__.cpython-37.pyc,,
> engineio/async_drivers/__pycache__/aiohttp.cpython-37.pyc,,
> engineio/async_drivers/__pycache__/asgi.cpython-37.pyc,,
> engineio/async_drivers/__pycache__/eventlet.cpython-37.pyc,,
> engineio/async_drivers/__pycache__/gevent.cpython-37.pyc,,
> engineio/async_drivers/__pycache__/gevent_uwsgi.cpython-37.pyc,,
> engineio/async_drivers/__pycache__/sanic.cpython-37.pyc,,
> engineio/async_drivers/__pycache__/threading.cpython-37.pyc,,
> engineio/async_drivers/__pycache__/tornado.cpython-37.pyc,,
> engineio/async_drivers/aiohttp.py,sha256=ckLm9IrHxzD7rjNdSelmLkI8nghcKM96iNH2TOJ1LVU,3777
> engineio/async_drivers/asgi.py,sha256=CYsyOrT_Z63ThY9PcnHYVfLmdxf0O_HuU1xTE8zLJ_Y,8010
> engineio/async_drivers/eventlet.py,sha256=rzndk316vSWrioXe7Aj-0artwnoDiQcRf5VoLDuPzEc,981
> engineio/async_drivers/gevent.py,sha256=4V4oUbHMFEtn13Pf9ZDiWhl2PRFpsP1sJ6-6lw2JO98,1803
> engineio/async_drivers/gevent_uwsgi.py,sha256=agWDGowbc1IEPg1Gk3pfe6e7rZq5_kANAM6I4ZCSyPU,5404
> engineio/async_drivers/sanic.py,sha256=8T8W2DRnmEJcTq6G2-TL22n6T9iD8K72uqI5QUZ2XkU,4328
> engineio/async_drivers/threading.py,sha256=URNHqrYV7oTvHWYEr7-JjqfAiKdWJG2SlAy-wuluncA,339
> engineio/async_drivers/tornado.py,sha256=Hvyi-6UZ4f1aAH67nKs-RlPfYBJ-tLY45TRuOxqthlI,5971
> engineio/async_eventlet.py,sha256=VncByIejG9w1Yq5xXvrKWCXeWLMijS0y4Qskr-S-FZ0,1023
> engineio/async_gevent.py,sha256=A_2cvNtktrVmYNz3KWgGmT52hxTn6uRgP39PeI_F6Tc,1869
> engineio/async_gevent_uwsgi.py,sha256=RGwq6ar95JDCmEbaKGJEZZmGUofukH6G5UCgwO1vJpU,5469
> engineio/async_sanic.py,sha256=DSB82jLZpZBhEudwNh1m05N8enbCmevbqR3RRoU8olc,4406
> engineio/async_threading.py,sha256=RwdgOVRieguNyK25hdxOaaSybIUxROexeBwDmi1KxvE,408
> engineio/async_tornado.py,sha256=zJubyhPrJHdEp7_MVkEQdScr89mjr6Y8IySs7K1Pcg8,4645
> engineio/asyncio_client.py,sha256=Y_TDmAnsBpha-FWJtNMzAuhBO5N0z6Agu8TlFqt9riQ,24318
> engineio/asyncio_server.py,sha256=6fmRGJcmnQ9yGlsqgz0wOXSPwDKM7ILJ5Y8pCIEFy6s,20469
> engineio/asyncio_socket.py,sha256=cu8bapwmKEMW66YDFLH6rG4jEUx8fy5DnLY2S0st4HU,9651
> engineio/client.py,sha256=iQu99oAujLMo37WhKmJRxUK884a9IP1L4vK-lrCd6Ic,26813
> engineio/exceptions.py,sha256=FyuMb5qhX9CUYP3fEoe1m-faU96ApdQTSbblaaoo8LA,292
> engineio/middleware.py,sha256=n8GQMkva4EmgBB1Bcm6W-sgYg9ADkGU_Wrfd03dS1qI,3788
> engineio/packet.py,sha256=2_vXHP7YbY3XP8OizlADSRLmwpoMJfQiWffC_Nc-gis,3506
> engineio/payload.py,sha256=12YbTQk0XH5pVP-9WcdCV008CgRi3PXc3vCBfpwNuxU,3106
> engineio/server.py,sha256=Mo7y1_82ifovnMyuoKAOqnXkrY5tA2k08qNdqOzalMg,28637
> engineio/socket.py,sha256=67TgODnQsVmHyC19bsRW7RQWyDAacoRIb9TGlTF6uR4,9807
> engineio/static_files.py,sha256=LDhgJhsjJxsMSdOEZJmu_sq7t9geYk4ij5W_XwRJpAA,1851
> python_engineio-3.10.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
> python_engineio-3.10.0.dist-info/LICENSE,sha256=yel9Pbwfu82094CLKCzWRtuIev9PUxP-a76NTDFAWpw,1082
> python_engineio-3.10.0.dist-info/METADATA,sha256=QylPi4iwl9Q_43b-Rhc6QJcTuPjoR3YhV1CzE_VmB2U,1863
> python_engineio-3.10.0.dist-info/RECORD,,
> python_engineio-3.10.0.dist-info/WHEEL,sha256=8zNYZbwQSXoB9IfXOjPfeNwvAsALAjffgk27FqvCWbo,110
> python_engineio-3.10.0.dist-info/top_level.txt,sha256=u8PmNisCZLwRYcWrNLe9wutQ2tt4zNi8IH362c-HWuA,9
**> tests/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
> tests/__pycache__/__init__.cpython-37.pyc,,
> tests/__pycache__/test_async_aiohttp.cpython-37.pyc,,
> tests/__pycache__/test_async_asgi.cpython-37.pyc,,
> tests/__pycache__/test_async_eventlet.cpython-37.pyc,,
> tests/__pycache__/test_async_tornado.cpython-37.pyc,,
> tests/__pycache__/test_asyncio_client.cpython-37.pyc,,
> tests/__pycache__/test_asyncio_server.cpython-37.pyc,,
> tests/__pycache__/test_asyncio_socket.cpython-37.pyc,,
> tests/__pycache__/test_client.cpython-37.pyc,,
> tests/__pycache__/test_middleware.cpython-37.pyc,,
> tests/__pycache__/test_packet.cpython-37.pyc,,
> tests/__pycache__/test_payload.cpython-37.pyc,,
> tests/__pycache__/test_server.cpython-37.pyc,,
> tests/__pycache__/test_socket.cpython-37.pyc,,
> tests/asyncio/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
> tests/asyncio/__pycache__/__init__.cpython-37.pyc,,
> tests/asyncio/__pycache__/test_async_aiohttp.cpython-37.pyc,,
> tests/asyncio/__pycache__/test_async_asgi.cpython-37.pyc,,
> tests/asyncio/__pycache__/test_async_tornado.cpython-37.pyc,,
> tests/asyncio/__pycache__/test_asyncio_client.cpython-37.pyc,,
> tests/asyncio/__pycache__/test_asyncio_server.cpython-37.pyc,,
> tests/asyncio/__pycache__/test_asyncio_socket.cpython-37.pyc,,**
> tests/asyncio/test_async_aiohttp.py,sha256=Stu9buAUVQMxhh4QhM9DIm_hHgtf5eyWZRVtzysyZpk,2145
> tests/asyncio/test_async_asgi.py,sha256=98UqlxxBXW8WW2c8xjcrMgcaB4vfmARgeYupKJmFKQk,11054
> tests/asyncio/test_async_tornado.py,sha256=qmMnPqQdiLPLILFdpoNBga0fXLhLKr-QGNu-vKlmY2c,2564
> tests/asyncio/test_asyncio_client.py,sha256=irvxMZilImQrGVG-lF99-YSDVtueCEAoqo77Emr6T-w,46478
> tests/asyncio/test_asyncio_server.py,sha256=BqD71iKOTreX7icDxWIanmptRrputRxg3ra8uYjziCk,39791
> tests/asyncio/test_asyncio_socket.py,sha256=h1Xiv-ld_ZxYsmobmKcrm9Gbs8UbYhGT3OUjOOpY3gA,17900
> tests/common/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
> tests/common/__pycache__/__init__.cpython-37.pyc,,
> tests/common/__pycache__/test_async_eventlet.cpython-37.pyc,,
> tests/common/__pycache__/test_client.cpython-37.pyc,,
> tests/common/__pycache__/test_middleware.cpython-37.pyc,,
> tests/common/__pycache__/test_packet.cpython-37.pyc,,
> tests/common/__pycache__/test_payload.cpython-37.pyc,,
> tests/common/__pycache__/test_server.cpython-37.pyc,,
> tests/common/__pycache__/test_socket.cpython-37.pyc,,
> tests/common/test_async_eventlet.py,sha256=MX6BQ_cFangqazawV_N74Z0c3NGV56rKvZ81pO3fIUE,931
> tests/common/test_client.py,sha256=Gjg9eNqGexry4jruc7kIcXXFvf7mBVzvjIb4e0R-SOk,44678
> tests/common/test_middleware.py,sha256=qM5FuHEKHMe5Qhf-46Ops5Nd2U5CxXsgNHWh3N1xP5U,6627
> tests/common/test_packet.py,sha256=gGIAGeadOEYwkYoy0FkOJ1odhg2R0WKTyeRC2a3eC-k,4213
> tests/common/test_payload.py,sha256=hFOphopZHI3-8k87VjnkoxpUQNUBoqpv15c4MJwRCSE,2660
> tests/common/test_server.py,sha256=XMjfOSlA6sepui8jYtFXIgOH1-KM5yW_BoU9vrKmP7g,39901
> tests/common/test_socket.py,sha256=932iHDZCKury_J91HZsv3wAwmiqBiSD6wYo8h-l9A9o,16964
> tests/test_async_aiohttp.py,sha256=Stu9buAUVQMxhh4QhM9DIm_hHgtf5eyWZRVtzysyZpk,2145
> tests/test_async_asgi.py,sha256=laXGVZUPqlmh1qdmsssiWxplEnOJd_ldrLU2h_nf9mo,9466
> tests/test_async_eventlet.py,sha256=MX6BQ_cFangqazawV_N74Z0c3NGV56rKvZ81pO3fIUE,931
> tests/test_async_tornado.py,sha256=qmMnPqQdiLPLILFdpoNBga0fXLhLKr-QGNu-vKlmY2c,2564
> tests/test_asyncio_client.py,sha256=iEaRNB4RR9XFDWefxCymvNN1FBHBwvXqaVExIxXI5HI,43609
> tests/test_asyncio_server.py,sha256=8eIjZL-Wd85qXm_W8InKkW7xUylMi4V1IKNlzmr1Wt0,38585
> tests/test_asyncio_socket.py,sha256=DkiZCc7QxIZzIHirGd4RYM3AbQG-sqpi0xq8J4l50_M,17130
> tests/test_client.py,sha256=RDRfzhGT9vG1VbcxDdHMmgTZhYD5q7r9SrPtQNoXW-I,41551
> tests/test_middleware.py,sha256=2s4y2uRp6vsbYXBZFi5Mem7q2kWYFhVYlImaQjsHmTo,5046
> tests/test_packet.py,sha256=gGIAGeadOEYwkYoy0FkOJ1odhg2R0WKTyeRC2a3eC-k,4213
> tests/test_payload.py,sha256=3COS8C85848pcHJqo45KIl8YfO32eALg8gup7hXMRRU,2084
> tests/test_server.py,sha256=ohrbLkFLB6_grAMK9MHHDIRRH0n28Baz1LbDGBzbdqE,37308
> tests/test_socket.py,sha256=ykqpYewUyUZekAGjHVveCvjSS4SWxIlkUrSbHRDUcz8,16115

As you can see it will create a "tests" folder in site-packages with your tests.

This results in the following:
- since some projects use the deprecated test_suite syntax they will overwrite each other in the site-packages\tests
- conflicts when having this installed in site-packages and running your own projects tests, which are very often in tests folder. it will now run your tests instead of own projects tests
- additional unneeded disk space usage and takes longer to install

All in all it's recommended to exclude tests when uploading to pypi.

**Comment by chrisoro** [comment]
I'm not sure how you build your wheel before uploading but if I'm simply running
`python setup.py bdist_wheel`
using Python 3.7.5 and setuptools 42.0.2 it won't add tests. This might be to the deprecated test_suite definition in your setup.py

**Comment by miguelgrinberg** [comment]
Interesting, I never noticed.

I have changed my laptop since the last time I released. On the new laptop I do not see the tests directory getting included in the wheel, probably because I'm using 3.7 (I believe I was running the release script under 3.6 previously).

**Comment by chrisoro** [comment]
Awesome, thank you!
