### ISSUE TITLE
logger can't be disabled

### ISSUE THREAD

**Issue by buckle2000** [miguelgrinberg/python-engineio#158]
The following code treats `logger=False` as `logger=True`.

https://github.com/miguelgrinberg/python-engineio/blob/a67b3d76d80e665ec071292dc4aadffb50be6d3f/engineio/client.py#L104-L114

The docstring says otherwise:

https://github.com/miguelgrinberg/python-engineio/blob/a67b3d76d80e665ec071292dc4aadffb50be6d3f/engineio/client.py#L58-L60

**Comment by buckle2000** [comment]
This is the same for server of this module and client and server of python-socketio.

A simple work around is to use `unittest.mock.Mock`

**Comment by miguelgrinberg** [comment]
Errors cannot be disabled, setting logger to `False` just silences anything below ERROR level. But you are correct in that the documentation does not explain this, I'll fix it.
