### ISSUE TITLE
Check cors_allowed_origins with problem

### ISSUE THREAD

**Issue by achivkin** [miguelgrinberg/python-engineio#165]
Hello. You have problem with check var cors_allowed_origins. 
File: asyncio_server.py 
Number: 193
self.cors_allowed_origins by default set None. check is made only "!=[]"
You need check 
self.cors_allowed_origins != [] and self.cors_allowed_origins != None

otherwise requests are blocked

Python: 3.8.2
Version engineio: 3.11.2

**Comment by miguelgrinberg** [comment]
Do you have an example where this server makes the wrong decision? The `None` check is done later, in an auxiliary function.

**Comment by achivkin** [comment]
I'm making a request from node.js local server vue js localhost:8087 to tornado socket io external_ip:8888
I am use your example code for Tornado.
First socket connect success, but emit not working. No errors are written. Nothing just works. I started to look at the code and realized at what point the connection crashed.

**Comment by miguelgrinberg** [comment]
You are making a cross-origin call. Why would that work if you don't configure CORS? Set `cors_allowed_origins='http://localhost:8087'` to register your Node server as allowed.

**Comment by achivkin** [comment]
Oh, I thought CORS was off by deafault. OK, i got. I am should 
socketio.AsyncServer(async_mode='tornado', logger=True, cors_allowed_origins=[])

**Comment by miguelgrinberg** [comment]
Sorry, but why would you want to disable CORS completely? If this is anything other than a quick test on a private network then I suggest you use my recommendation instead.

**Comment by achivkin** [comment]
Tornado will be closed from outside. Proxy nginx. At nginx will be make cors rules.

**Comment by miguelgrinberg** [comment]
I don't think nginx has a strong CORS implementation. All you can do is insert CORS headers. There's nothing there to do validate origins. Keep in mind that browsers do not implement CORS for WebSocket, so regardless of what you of what you do in nginx, if you disable CORS in your server you are likely going to be accepting connections from anyone.
