### ISSUE TITLE
Binary data is printed in the console

### ISSUE THREAD

**Issue by fredericsureau** [miguelgrinberg/python-engineio#17]
Packets data are always logged even when data is binary or very long.
When printing the binary-containing logs into the console, it completely fucks up my terminal.

What about displaying binary data using repr()?
Clipping very long messages could be useful too.

**Comment by miguelgrinberg** [comment]
Just to make sure we are talking about the same thing, do you mean the logging that is done here? https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/socket.py#L40-L42

I agree, I did not consider the data can be long and have unprintable characters in it. But of course, the workaround is to turn logging off.

**Comment by fredericsureau** [comment]
Yes I was talking about this log message.

Thanks for the patch!
