### ISSUE TITLE
Failing to parse cookie with an equal in its value

### ISSUE THREAD

**Issue by ignapas** [miguelgrinberg/python-engineio#174]
This line
https://github.com/miguelgrinberg/python-engineio/blob/7fa9575954f4e14794d5458107522d858c08f69e/engineio/asyncio_client.py#L252
causes a cookie with an equal in its value to throw an exception like
``ValueError: dictionary update sequence element #0 has length 3; 2 is required``

The fix for that could be:
```
[cookie.split('=', 1) for cookie in value.split('; ')])
```

**Comment by miguelgrinberg** [comment]
Yes, I agree. I'll fix it. Thanks!

**Comment by ignapas** [comment]
> Yes, I agree. I'll fix it. Thanks!

PRed

**Comment by miguelgrinberg** [comment]
Awesome, thank you for taking care of it!
