### ISSUE TITLE
Bug TypeError: translate_request() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by PhpEssential** [miguelgrinberg/python-engineio#178]
Hi I think you have a bug here:

https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/async_drivers/aiohttp.py
def translate_request(request):

sould be like that:
async def translate_request(scope, receive, send):

**Comment by miguelgrinberg** [comment]
Can you show me your code, at least how you create your `AsyncServer` object, and how you start the server?

**Comment by PhpEssential** [comment]
I think is my fault, the problem occurs when i installed aiohttp, i need to have a client and server in same app. When i installed it, the default async driver switch to aiohttp.py. I added async_mode='asgi' and it's work
`
ws_server = socketio.AsyncServer(cors_allowed_origins='*', async_mode='asgi')
app = socketio.ASGIApp(ws_server)
uvicorn.run(app, host=configuration[Config.BIND_HOST], port=configuration[Config.BIND_PORT])
`

**Comment by miguelgrinberg** [comment]
Your solution is the correct one, the package can't always guess what is the correct async mode you want. Glad you figured it out.

**Comment by PhpEssential** [comment]
Maybe you can change it on the fly in the AsyncServer when this function is called "app = socketio.ASGIApp(ws_server)"?

**Comment by miguelgrinberg** [comment]
By that time the async mode has already been determined. There might be ways to improve the auto-selection process, but right now this process happens in the `Server` and `AsyncServer` constructors. It would need to be moved to later in the process.
