### ISSUE TITLE
Ping/Pong timeout problem

### ISSUE THREAD

**Issue by krishnavelu** [miguelgrinberg/python-engineio#183]
The server sets the pingInterval & pingTimout, but engineio doesn't use pingTimout for timeout. Instead it uses pingInterval for timeout.

https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/client.py#L534-L544

![image](https://user-images.githubusercontent.com/38440742/87998357-a3946180-cac5-11ea-89bb-d5f474ce7bef.png)

`self.ping_loog_event` is on wait for `self.ping_interval` time, if the pong is not received for `self.ping_interval` time, `ws` is closed and while loop is exited.

Here is the log with timing to prove this.

```
pydev debugger: starting (pid: 57432)
23:14:10.55.779, client, INFO, WebSocket connection accepted with {'sid': 'B_k-Wy8NwJrpkfSaAAYD', 'upgrades': [], 'pingInterval': 2000, 'pingTimeout': 60000}		- pingInterval : 2 seconds, pingTimeout : 60 seconds
23:14:10.55.779, client, INFO, Engine.IO connection established
23:14:10.57.774, client, INFO, Sending packet PING data None
23:14:10.61.764, client, INFO, Received packet MESSAGE data 0


23:52:39.613.351, client, INFO, Sending packet PING data None
23:52:39.830.123, client, INFO, Received packet PONG data None
23:52:41.614.032, client, INFO, Sending packet PING data None
23:52:41.830.636, client, INFO, Received packet PONG data None
23:52:43.614.457, client, INFO, Sending packet PING data None
23:52:43.832.420, client, INFO, Received packet PONG data None
23:52:45.615.007, client, INFO, Sending packet PING data None
23:52:45.831.851, client, INFO, Received packet PONG data None
23:52:47.615.802, client, INFO, Sending packet PING data None
23:52:47.918.927, client, INFO, Received packet PONG data None
23:52:49.616.014, client, INFO, Sending packet PING data None
23:52:49.833.062, client, INFO, Received packet PONG data None
23:52:51.616.422, client, INFO, Sending packet PING data None					- last ping sent
23:52:53.617.275, client, INFO, PONG response has not been received, aborting	- after 2 second (pingInterval) PONG response has not been received, its aborting. This should happen after 60 seconds (pingTimeout).
23:52:53.617.275, client, INFO, Exiting ping task
23:52:53.618.242, client, INFO, Exiting write loop task
23:52:53.619.240, client, INFO, Unexpected error "[WinError 10004] A blocking operation was interrupted by a call to WSACancelBlockingCall", aborting
23:52:53.620.236, client, INFO, Waiting for write loop task to end
23:52:53.620.236, client, INFO, Waiting for ping loop task to end
23:52:53.621.235, client, INFO, Engine.IO connection dropped

```

**Comment by krishnavelu** [comment]
Solved in this [PR](https://github.com/miguelgrinberg/python-engineio/pull/184)
Please accept if its correct.

I've also tested this and here is the log after fixing.


```
23:08:44.935.833, client, INFO, WebSocket connection accepted with {'sid': '6xkpv3L0bJHNxNItAAXb', 'upgrades': [], 'pingInterval': 2000, 'pingTimeout': 60000}

23:04:01.550.669, client, INFO, Sending packet PING data None
23:04:01.773.771, client, INFO, Received packet PONG data None
23:04:03.551.202, client, INFO, Sending packet PING data None
23:04:03.791.683, client, INFO, Received packet PONG data None
23:04:05.551.485, client, INFO, Sending packet PING data None
23:04:05.772.195, client, INFO, Received packet PONG data None
23:04:07.552.214, client, INFO, Sending packet PING data None
23:04:07.773.653, client, INFO, Received packet PONG data None
23:04:09.552.320, client, INFO, Sending packet PING data None
23:04:09.921.125, client, INFO, Received packet PONG data None
23:04:11.553.061, client, INFO, Sending packet PING data None
23:04:11.789.702, client, INFO, Received packet PONG data None
23:04:13.553.082, client, INFO, Sending packet PING data None
23:04:13.775.046, client, INFO, Received packet PONG data None   - Last received PONG
23:04:15.553.353, client, INFO, Sending packet PING data None
23:04:17.553.763, client, INFO, Sending packet PING data None
23:04:19.554.361, client, INFO, Sending packet PING data None
23:04:21.554.529, client, INFO, Sending packet PING data None
23:04:23.555.107, client, INFO, Sending packet PING data None
23:04:25.555.151, client, INFO, Sending packet PING data None
23:04:27.555.285, client, INFO, Sending packet PING data None
23:04:29.555.298, client, INFO, Sending packet PING data None
23:04:31.555.833, client, INFO, Sending packet PING data None
23:04:33.556.447, client, INFO, Sending packet PING data None
23:04:35.557.909, client, INFO, Sending packet PING data None
23:04:37.557.962, client, INFO, Sending packet PING data None
23:04:39.558.652, client, INFO, Sending packet PING data None
23:04:41.559.633, client, INFO, Sending packet PING data None
23:04:43.559.961, client, INFO, Sending packet PING data None
23:04:45.560.863, client, INFO, Sending packet PING data None
23:04:47.561.369, client, INFO, Sending packet PING data None
23:04:49.562.346, client, INFO, Sending packet PING data None
23:04:51.563.099, client, INFO, Sending packet PING data None
23:04:53.563.779, client, INFO, Sending packet PING data None
23:04:55.563.959, client, INFO, Sending packet PING data None
23:04:57.564.796, client, INFO, Sending packet PING data None
23:04:59.565.486, client, INFO, Sending packet PING data None
23:05:01.566.345, client, INFO, Sending packet PING data None
23:05:03.567.161, client, INFO, Sending packet PING data None
23:05:05.567.810, client, INFO, Sending packet PING data None
23:05:07.568.145, client, INFO, Sending packet PING data None
23:05:09.568.336, client, INFO, Sending packet PING data None
23:05:11.568.646, client, INFO, Sending packet PING data None
23:05:13.569.457, client, INFO, Sending packet PING data None
23:05:15.569.640, client, INFO, PONG response has not been received, aborting    -   Now it timesout  after 60 seconds (pingTimout)
23:05:15.569.640, client, INFO, Exiting ping task
23:05:15.570.510, client, INFO, Exiting write loop task
23:05:15.571.506, client, INFO, Unexpected error "[WinError 10004] A blocking operation was interrupted by a call to WSACancelBlockingCall", aborting
23:05:15.572.535, client, INFO, Waiting for write loop task to end
23:05:15.572.535, client, INFO, Waiting for ping loop task to end
23:05:15.572.535, client, INFO, Engine.IO connection dropped
```

Now it timesout  after 60 seconds (pingTimout)

**Comment by miguelgrinberg** [comment]
Is this causing any problems? I believe this is a matter of interpretation. I take `ping_timeout` as the amount of time the server waits for the client to send a ping to the server. So basically, the server is asking the client to send a ping every `ping_interval` seconds approximately and to never delay a ping by more than `ping_timeout` seconds, at which point the server will close the connection.

**Comment by krishnavelu** [comment]
Yes, it’s causing problems. For a highly loaded server which is unable to send pong back to the client within ping intervel time, the engineio disconnects frequently.
This is what I’ve shown in the log.

**Comment by krishnavelu** [comment]
> I take ping_timeout as the amount of time the server waits for the client to send a ping to the server.

Yes, but the implementation says different. It says, if pong is not received in ping interval time, disconnect the WS.

**Comment by miguelgrinberg** [comment]
The reference implementation in Node.js uses 60s for the interval and 5s for the timeout. I was actually considering switching to use the same numbers, since having a timeout that is larger than the interval makes really no sense.

I would think that if your server is unable to respond to the PING in 25 seconds you have a serious problem with server responsiveness that you need to fix.

Also consider that there are big changes coming in the next revision of the Socket.IO protocol, where the server will be sending the PING packets and the client replying with PONGs, so all of this is going to need to change.

**Comment by krishnavelu** [comment]
Please see the logs. Server sets ping interval as 2 seconds and ping timeout as 60 seconds. Ideally ping Interval should be less than ping timeout, not the reverse. In this case if engineio is not able to receive pong in 2 seconds (which happens more frequently, at-least 50-100 times a day), it disconnects.

Note: I’m using only client side of the library. I’m communicating to a server which I don’t have control with. So I cannot do anything in the server side.

**Comment by krishnavelu** [comment]
engineio JS implementation.

https://github.com/socketio/engine.io/blob/master/lib/socket.js#L118-L119

>  Pings client every `this.pingInterval` and expects response
>  within `this.pingTimeout` or closes connection.

**Comment by miguelgrinberg** [comment]
> Ideally ping Interval should be less than ping timeout, not the reverse.

Why? Where did you get this from? As I said, the defaults for the JS implementation is 60s for interval and 5s for timeout.

> engineio JS implementation.

Did you read the code you linked? Every time it sends a ping it resets the timeout timer. So effectively, if you use a timeout that is longer that the interval then the timeout is completely disabled.

In your implementation the client continues sending pings even if previous pings haven't been responded, which makes no sense to me. I understand the problem that you have and would love to offer you a solution, but in my view, it isn't correct to have more than one outstanding ping.

You should check with whoever is in charge of the server you are using regarding the 2 second interval setting. That is a very bad choice, as it generates a lot of noise in the transport.

**Comment by krishnavelu** [comment]
> Why? Where did you get this from? As I said, the defaults for the JS implementation is 25s for interval and 5s for timeout.

I may be wrong in this. And my understanding is also different as I see the server's 2 & 60 seconds ping times.
Whatever it may be "pingInterval > pingTimeout" or "pingTimeout > pingInterval", **the client should use pingTimout for timeout not pingInterval for timeout.**

> Did you read the code you linked? Every time it sends a ping it resets the timeout timer.

Yes I read it. [This](https://github.com/socketio/engine.io/blob/master/lib/socket.js#L131 ) line uses pingTimout to reset, not pingInterval.  But engineio uses pingInterval to timeout.

> In your implementation the client continues sending pings even if previous pings haven't been responded,

This is just in case server missed 1 ping, client may never receive a pong again. Eventually it times out and closes the connection. There is no harm in sending another ping even if you didn't receive a pong response from server.

> You should check with whoever is in charge of the server you are using regarding the 2 second interval setting. That is a very bad choice, as it generates a lot of noise in the transport.

As I said I have no control over the server. I cannot even request them and point out your "pingTimeout > pingInterval" please correct that. I cannot request.

But this implementation solves my problem of frequent disconnection from the server.

How about this? In the [read_loop()](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/client.py#L547) function and [write_loop()](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/client.py#L633), you've used a max of [timeouts](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/client.py#L554) Even that would work and solve the problem for me.

But I would recommend we should use only pingTimout for timeout, not max or pingInterval.
I agree my fix will not work for the case pingInterval > pingTimeout. But if you agree on the fact that we should use only pingTimout for timeout and not pingInterval, I can modify my implementation so that it works for both the cases and uses only pingTimout for timeout.

**Comment by miguelgrinberg** [comment]
Let me start with this. If you found that by changing this project in certain way you get a better result, then by all means, use your modified version of the package. It's perfectly fine to do that, you would not be the only one.

What we are discussing here is a change that will apply to every user of this project, not your particular case. I hope we are clear on this.

> Whatever it may be "pingInterval > pingTimeout" or "pingTimeout > pingInterval", the client should use pingTimout for timeout not pingInterval for timeout.

You are telling me that you think it is okay for several ping packets to go unanswered if the ping timeout is much longer than the ping interval. I disagree. I do not believe this is a correct approach. Every ping must be responded with a pong, and until the pong arrives the client should not send another ping.

> Yes I read it. This line uses pingTimout to reset, not pingInterval. But engineio uses pingInterval to timeout.

My point is that this JS code is designed to work only when pingTimeout < pingInterval. When you have the reverse, the pingTimeout will never trigger, so their implementation is buggy and does not do what you want this project to do.

> As I said I have no control over the server.

You seem to be in a bad situation with this server you are connecting to. The (2s, 60s) timeouts that were configured in this server make absolutely no sense. But that is not what we are discussing here.

> How about this? In the read_loop() function and write_loop(), you've used a max of timeouts

Those are not disconnection timeouts. The purpose of the max() there is to make sure that we wait long enough on the requests to let any other timeouts kick in first. I could do 2 times the max and it would still work.

> But if you agree on the fact that we should use only pingTimout for timeout and not pingInterval

I can agree with this statement at a high-level, and this is certainly correct when pingTimeout < pingInterval, but I don't agree to let ping packets go unanswered, so I don't see how we can make this work. Sorry.

**Comment by krishnavelu** [comment]
Can you please explain why is pingInterval used as timeout and not pingTimeout?

**Comment by miguelgrinberg** [comment]
There is really nothing else I can say that I haven't said before.

**Comment by krishnavelu** [comment]
I have the answer above, but I was expecting the same answer from above, so that we can just concentrate on one thing.

>  I believe this is a matter of interpretation. I take ping_timeout as the amount of time the server waits for the client to send a ping to the server. So basically, the server is asking the client to send a ping every ping_interval seconds approximately and to never delay a ping by more than ping_timeout seconds, at which point the server will close the connection.

As per the Node.js default times
`pingInterval : 60 Secs`
`pingTimeout : 5 Secs`
1. If the server is telling the client to send ping in every 60 seconds, why would the server timeout  in 5 seconds itself?
2. If the `pingTimeout` is to be used by server itself, why would it send to client?

**Comment by miguelgrinberg** [comment]
The defaults in the Node server are (25, 5). They used to be (25, 60) a few years ago.

> If the server is telling the client to send ping in every 60 seconds, why would the server timeout in 5 seconds itself?

The server is telling the client to send a ping every 25 seconds. The expected time for the pong to be sent back by the server is 5 seconds or less.

Long ago, when the timeout was 60 seconds, the server used it instead of the ping interval. I copied this behavior several years ago. Since then, the node server realized that the (25, 60) numbers didn't make a lot of sense, and switched to (25, 5). I have not made the switch yet but plan to. When I make this change, the timeout used by the server to kill clients is going to be either `pingInterval` or `max(pingInterval, pingTimeout)`, I haven't decided which is better yet.

> If the pingTimeout is to be used by server itself, why would it send to client?

The `pingTimeout` is provided to clients with the intention that they will use it, but it needs to be less than `pingInterval` to be useful. You saw in the JS client that a timeout that is larger than the interval effectively deactivates any timeouts on the client side.

It was my choice in the Python client to ignore `pingTimeout` and give the server extra time to respond, up to `pingInterval` seconds, regardless of how `pingTimeout` is set. As I said before, a longer `pingTimeout` makes no sense because you would have pings w/o a matching pong, and a shorter `pingTimeout` can be safely extended all the way to `pingInterval` without affecting anything, and this sometimes helps prevent disconnections in unreliable networks such as mobile.
