### ISSUE TITLE
Dash in flask 

### ISSUE THREAD

**Issue by Full-Stack-dev410** [miguelgrinberg/python-engineio#187]
When using dash in flask app:
i have get some errors:

`app.py:6: DeprecationWarning: The import 'werkzeug.wsgi.DispatcherMiddleware' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.wsgi.middleware.dispatcher import DispatcherMiddleware' instead.
  from werkzeug.wsgi import DispatcherMiddleware
Traceback (most recent call last):
  File "app.py", line 24, in <module>
    dash_app1 = protect_views(dash_app1)
  File "app.py", line 18, in protect_views
    if view_func.startswith(app1.url_base_pathname):
AttributeError: 'Dash' object has no attribute 'url_base_pathname'`

dash version is 1.0.0

my code :

`app = flask.Flask(__name__)
app.secret_key = 'MySecret'

def protect_views(app1):
    for view_func in app1.server.view_functions:
        if view_func.startswith(app1.url_base_pathname):
            app1.server.view_functions[view_func]
    return app1

dash_app1 = dash.Dash(__name__, server = app, url_base_pathname='/page_one/')
dash_app1.layout = app1.layout
dash_app1 = protect_views(dash_app1)`
If you are know this, please help me
thanks

**Comment by miguelgrinberg** [comment]
This is an issue board for the python-engineio project, not for Flask. Try the discord channel for Flask, you may find help there.
