### ISSUE TITLE
Threading memory leak in CPython 3.7+

### ISSUE THREAD

**Issue by harmon** [miguelgrinberg/python-engineio#188]
Affects: client.py

We ran into an issue on a long-running ~server~ process using the SocketIO client.py module where memory would grow and grow unexpectedly. After `tracemalloc`-ing the heck out of it, I discovered that a change in Python 3.7 (I think 3.7.4+ technically?) held onto thread WeakRef references until the process exited if "join()" was never called on them. It caused a slow memory leak. We have to revert back to Python 3.6 to get around this issue.

Just wanted to mention that here with a recommendation to mention this in the README/docs of engineio and socketio, and maybe suggest looking into Daemon threads. I understand the benefit of using normal threads, as it will block the process until they finish up, which is a nice behavior, so I don't think Daemon threads are really the best way to go.

There's the issue: https://bugs.python.org/issue37788

There was a proposed solution by the original author of the code that caused the bug, but it seems it was rejected do to regression issues. I don't know if there's anyone working on this issue on the core team, so this might be a long-lived issue.

If you have any suggestions on how to get around this, I'm all ears. I'd love to upgrade to at least 3.7.

Thanks!!

**Comment by miguelgrinberg** [comment]
The only time threads are used is when you work with the 'threading' async mode, which is not intended for production use. So I really don't see how this bug applies to this Socket.IO server.

**Comment by harmon** [comment]
Every time a message is received, `engineio.client.Client` kicks off a new Thread to handle it:

Message packet handling:
https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/client.py#L455

Async trigger event handling:
https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/client.py#L493

Background task kicks off a new thread for each message:
https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/client.py#L259

So every EngineIO message we receive ends up creating a new thread. Over time, this ends up increasing memory slowly due to the bug I linked above. Since the Threads never have `join()` called on them, those references aren't cleaned up.

I hope I explained that clearly enough.

**Comment by harmon** [comment]
Maybe I should clarify: when I said "long-running server" I meant a long-running process (what I'm calling a "server" here) utilizing the python-socketio client library (socketio.client.Client), not the server.py module.

**Comment by miguelgrinberg** [comment]
Here is a possible solution. You can monkey-patch the `start_background_task()` method so that it creates daemon threads:

```python
    import engineio
    import socketio

    def my_start_background_task(self, target, *args, **kwargs):
        th = threading.Thread(target=target, args=args, kwargs=kwargs)
        th.daemon = True
        th.start()
        return th

    engineio.Client.start_background_task = my_start_background_task

    client = socketio.Client()  # this client will now create daemon threads
```

**Comment by harmon** [comment]
Yup, my bad! I updated my original comment as well in case anyone comes across this.

Sure, yes I could monkey patch it for now until Python fixes that issue. But I wanted to let you know that it's a potential problem for folks using EngineIO on any CPython 3.7+, and that it might be helpful to add a note to the documentation about it. I'm hoping they fix it sometime, but who knows. I'd be happy to submit a small PR for the docs with a note about this if you think it's appropriate.

Anyway, thanks for the quick responses, you are a refreshing outlier in the open source community :)
