### ISSUE TITLE
ASGI middleware support

### ISSUE THREAD

**Issue by Korijn** [miguelgrinberg/python-engineio#191]
In `engineio.async_drivers.asgi.ASGIApp.translate_request` the ASGI request `scope` is consumed and used to construct an `environ` object, which can be accessed in `connect` event handlers.

However, commonly speaking, [ASGI middleware](https://www.starlette.io/middleware/) such as `SessionMiddleware`, write their information to the ASGI request `scope` object. This is not accessible from the `environ` object and as such I can't benefit from middleware.

It would be very nice if the scope object were exposed to `connect` callbacks via the following simple change in `translate_request`:

```python
    environ = {
        # ...
        'scope': scope,
    }
```

For any future readers facing the same issue, I worked around this problem with an absolutely hideous hack:

```python
import inspect

@sio.event
def connect(sid, environ):
    scope = [f for f in inspect.stack() if f.function == "handle_request" and f.filename.endswith("asyncio_server.py")][-1].frame.f_locals['args'][0]
```

**Comment by miguelgrinberg** [comment]
This makes perfect sense. I'm already exposing the `send` and `receive` functions as `asgi.send` and `asgi.receive`, so we can add `asgi.scope`. Would you like to craft a PR for this?

**Comment by Korijn** [comment]
See #192
