### ISSUE TITLE
Async client ignores ctrl-c after connect fails

### ISSUE THREAD

**Issue by JoriDubrovin** [miguelgrinberg/python-engineio#197]
My code tries to connect with `socketio.AsyncClient`, and if that fails, sleeps a few seconds before trying again.  With python-engineio 3.13.2, if the user presses ctrl-c during the sleep, the program does not stop but just prints ^C.

Like #196, this seems to be related to the call to `add_signal_handler`.

This is my `script.py`:
```
import asyncio
import socketio

async def try_connect():
    sio = socketio.AsyncClient()
    try:
        await sio.connect(url='file:///')
    except Exception as e:
        print(e)
    await asyncio.sleep(4)

asyncio.get_event_loop().run_until_complete(try_connect())
```

To reproduce with Python 3.7.3 on Debian buster:
```
> python3 -m venv no-ctrl-c
> source no-ctrl-c/bin/activate
> pip install python-engineio==3.13.2 python-socketio==4.6.0 aiohttp==3.6.2
> python script.py
Connection refused by the server
^C^C^C^C^C
```

If I replace `python-engineio==3.13.2` with the previous version 3.13.1, then ctrl-c stops the program with a `KeyboardInterrupt`, as expected.

**Comment by miguelgrinberg** [comment]
Thanks. I have it in my list to review the signal handling changes so I'll have an update on this soon.
