### ISSUE TITLE
ImportError JSONDecodeError when using Python 2.7

### ISSUE THREAD

**Issue by mddarmawan** [miguelgrinberg/python-engineio#206]
> TL;DR - I know Python 2.7 was near to its end of life, but our company still using Python 2.7 for a specified application, so I have used this workaround. Will full-upgrade to Python 3 later.

I was using python-engineio for my application without knowing it's version. Today one of my team is re-deployed the application and got this error:

![image](https://user-images.githubusercontent.com/22543134/100999128-efd0d180-358e-11eb-8fca-ea91c730ca45.png)

After tracked the error, I realized that this command is not supported in Python 2.7 (#CMIIW):
`from json import JSONDecodeError`

To make sure, I have also tested on repl.it:
![image](https://user-images.githubusercontent.com/22543134/100999705-a339c600-358f-11eb-8754-e2fc150da222.png)

So my workaround is forcing using the *3.13.2* version rather than the newest version. For now, I don't know if I can use another best workaround for this problem.

Thank you.

**Comment by miguelgrinberg** [comment]
I'm not sure how I can help. Python 2 has reach its end of life several months ago, I will not be supporting it anymore.

**Comment by mddarmawan** [comment]
Thanks, @miguelgrinberg. I will close this issue for now.
