### ISSUE TITLE
Deprecate Python 3.5

### ISSUE THREAD

**Issue by Ezzer17** [miguelgrinberg/python-engineio#211]
On [readthedocs](https://python-engineio.readthedocs.io/en/latest/intro.html#server-features) it is stated that packages are compatible with Python 3.5+. However, Commit [0583c1e8](https://github.com/miguelgrinberg/python-engineio/commit/0583c1e8b122e4c7620e04429bf4f901bad551bd) adds import of [secrets](https://docs.python.org/3/library/secrets.html) module, which was added in Python 3.6. This makes python-engineio incompatible with Python 3.5. To avoid confusion, library documentation should probably be modified.

**Comment by miguelgrinberg** [comment]
Thanks, the references to Python 3.5 in the documentation are now removed.
