### ISSUE TITLE
Upgrade from 3.13 to 3.14 broke my stack

### ISSUE THREAD

**Issue by yoch** [miguelgrinberg/python-engineio#212]
Hi

My stack includes Apache 2.4 with mod_proxy_wstunnel and mod_wsgi enabled, and `socketio.Server(async_mode='eventlet')`.

I use python-socketio 4.6.1, and everything was fine before we upraded python-engineio to 3.14.

Now I get this error:
```
gserver[13442]: Server initialized for eventlet.
gserver[13442]: (13442) wsgi starting up on http://127.0.0.1:5555
gserver[13442]: (13442) accepted ('127.0.0.1', 55054)
gserver[13442]: Invalid transport websocket (further occurrences of this error will be logged with level INFO)
gserver[13442]: 86.245.33.173,127.0.0.1 - - [26/Jan/2021 14:56:26] "GET /socket.io/?EIO=3&transport=websocket HTTP/1.1" 400 245 0.000461
```

When reverted to 3.13 it works as excepted (upgrade to websocket successful):
```
gserver[14449]: 109.221.253.194,127.0.0.1 - - [26/Jan/2021 15:18:15] "GET /socket.io/?EIO=3&transport=websocket HTTP/1.1" 200 0 115.168811
```

**Comment by max-saccoccio-bg** [comment]
I believe this has been fixed here but not released in v3. We are awaiting a release in v3 to unpin from v3.13.2 as well: https://github.com/miguelgrinberg/python-engineio/commit/3d7ea22e8a9930544c711c5e124f75121b300ef3

Related issue + PR: 
* https://github.com/miguelgrinberg/python-engineio/issues/203 
* https://github.com/miguelgrinberg/python-engineio/pull/204

**Comment by miguelgrinberg** [comment]
@max-saccoccio-bg I will not be fixing backwards, I only apply fixes forward. You can upgrade python-engineio and python-socketio to their latest releases to have access to this fix. You will also need to upgrade your Socket.IO client at the same time, as there has been a major upgrade to the Socket.IO protocol as well.
