### ISSUE TITLE
Cross site scripting

### ISSUE THREAD

**Issue by chiu0602** [miguelgrinberg/python-engineio#223]
When query with `http://<IP>/socket.io/?sid=aaa<iframe+src%3Djavascript%3Aalert(999)>`, cross site scripting is found that the script block will be executed when the page loads in the user's browser.

```
"Invalid session aaa<iframe src=javascript:alert(999)>"
```

This may due to missing sanitizing the parameter `message` in `_bad_request()`.
[https://github.com/miguelgrinberg/python-engineio/blob/bd2e59d0b37e86fd561f716f2d805081200f896e/engineio/server.py#L637](https://github.com/miguelgrinberg/python-engineio/blob/bd2e59d0b37e86fd561f716f2d805081200f896e/engineio/server.py#L637)

**Comment by miguelgrinberg** [comment]
Did you notice that the content type is text/plain? How would this execute if the document is declared as just being text?

**Comment by chiu0602** [comment]
@miguelgrinberg You are right, thanks! Sorry for my false alarm.
