### ISSUE TITLE
AsyncClient overwrites http_session after disconnect

### ISSUE THREAD

**Issue by JoriDubrovin** [miguelgrinberg/python-engineio#226]
The `AsyncClient` constructor takes a `http_session` parameter for customizing the `aiohttp.ClientSession`.  This works for the first connection, but if the client is disconnected, then upcoming connections overwrite the session by a fresh `aiohttp.ClientSession()`, losing the customizations.

Should `http_session` be e.g. a function that constructs `ClientSession`s instead?

**Comment by miguelgrinberg** [comment]
I'll see if the original session can be preserved, so that a function isn't necessary.
