### ISSUE TITLE
gevent_uwsgi connection limit

### ISSUE THREAD

**Issue by youyueyinfeng** [miguelgrinberg/python-engineio#228]
Hi,  I found if almost more than 1024 clients connect to the server running using gevent_uwsgi, the extra clients will connect failed. After debugging, the below code will raise error since the connection_fd() return a value bigger than 1024.
```python
# spawn a select greenlet
def select_greenlet_runner(fd, event):
    """Sets event when data becomes available to read on fd."""
    while True:
        event.set()
        try:
            select([fd], [], [])[0]
        except ValueError:
            import traceback
            print(traceback.format_exc())
            break
self._select_greenlet = gevent.spawn(select_greenlet_runner, self._sock, self._event)
```
In this case, `gevent.select()` doesn't work, server has to recv the msg after `event.wait(timeout=3)`. If I pass a wait_timeout > 3 to `client.connect()`, the client can work,  while all the msgs are processed 3s latter. 

So I wonder if there's a way to advance this scene.

**Comment by miguelgrinberg** [comment]
Okay, sorry, I do understand now. This is very old code that I haven't seen in many years, I thought you were copying code from uWSGI.

I have changed the use of select to the `selectors` module. You will need to install python-engineio from the main branch to try this out. Let me know if this addresses the issue.

**Comment by youyueyinfeng** [comment]
Yeah, the new code in the main branch fix the problem. The `DefaultSelector` choose `EpollSelector` on my machine. Thanks a lot~
