### ISSUE TITLE
socketio_path of '/' fails in asgi.py

### ISSUE THREAD

**Issue by tobyX** [miguelgrinberg/python-engineio#242]
**Describe the bug**
I mount socket.io as an subapp in an FastAPI app. Because I serve REST next to websockets I need to mount them as different paths. I use a socket.io path of '/' which leads to a compare of / with // in [asgi.py](https://github.com/miguelgrinberg/python-engineio/blob/583c7db1f9dfa62290481634b4f9ab4d39a8ec6b/src/engineio/async_drivers/asgi.py#L53)

Used versions:

> python-engineio         4.2.0
> python-socketio         5.3.0

**To Reproduce**

Server:
```
import socketio
import uvicorn
from fastapi import FastAPI

sio = socketio.AsyncServer(async_mode="asgi", cors_allowed_origins='*')
app = FastAPI()
app.mount("/socket", socketio.ASGIApp(socketio_server=sio, socketio_path='/'))

if __name__ == "__main__":
    uvicorn.run(app, debug=True)
```

Client:
```
import socketio

sio = socketio.Client(logger=True, engineio_logger=True)
sio.connect("http://127.0.0.1:8000/", socketio_path='/socket', transports=['websocket'])
```

**Expected behavior**
Connect works and doesnt throws an exception on connect.

**Logs**

Server:
> [2021-07-26 16:12:50,193] INFO in uvicorn.error[server]: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
> [2021-07-26 16:12:52,308] DEBUG in websockets.protocol[protocol]: server - state = CONNECTING
> [2021-07-26 16:12:52,309] DEBUG in websockets.protocol[protocol]: server - event = connection_made(<_SelectorSocketTransport fd=1276 read=polling write=<idle, bufsize=0>>)
> [2021-07-26 16:12:52,309] DEBUG in websockets.protocol[protocol]: server - event = data_received(<238 bytes>)
> [2021-07-26 16:12:52,310] DEBUG in websockets.server[server]: server < GET /socket/?transport=websocket&EIO=4&t=1627308772.3015466 HTTP/1.1
> [2021-07-26 16:12:52,310] DEBUG in websockets.server[server]: server < Headers([('upgrade', 'websocket'), ('host', '127.0.0.1:8000'), ('origin', 'http://127.0.0.1:8000'), ('sec-websocket-key', 'mdTZuWzesQcuZ+pdUJXWsQ=='), ('sec-websocket-version', '13'), ('connection', 'Upgrade')])
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "C:\git\dev-env3.9\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 171, in run_asgi
>     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
>   File "C:\git\dev-env3.9\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__
>     return await self.app(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\uvicorn\middleware\debug.py", line 81, in __call__
>     return await self.app(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\fastapi\applications.py", line 199, in __call__
>     await super().__call__(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\starlette\applications.py", line 112, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\starlette\middleware\errors.py", line 146, in __call__
>     await self.app(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\starlette\exceptions.py", line 58, in __call__
>     await self.app(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\starlette\routing.py", line 580, in __call__
>     await route.handle(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\starlette\routing.py", line 390, in handle
>     await self.app(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\engineio\async_drivers\asgi.py", line 65, in __call__
>     await self.not_found(receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\engineio\async_drivers\asgi.py", line 107, in not_found
>     await send({'type': 'http.response.start',
>   File "C:\git\dev-env3.9\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 223, in asgi_send
>     raise RuntimeError(msg % message_type)
> RuntimeError: Expected ASGI message 'websocket.accept' or 'websocket.close', but got 'http.response.start'.
> [2021-07-26 16:12:52,318] ERROR in uvicorn.error[websockets_impl]: Exception in ASGI application
> Traceback (most recent call last):
>   File "C:\git\dev-env3.9\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 171, in run_asgi
>     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
>   File "C:\git\dev-env3.9\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__
>     return await self.app(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\uvicorn\middleware\debug.py", line 81, in __call__
>     return await self.app(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\fastapi\applications.py", line 199, in __call__
>     await super().__call__(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\starlette\applications.py", line 112, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\starlette\middleware\errors.py", line 146, in __call__
>     await self.app(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\starlette\exceptions.py", line 58, in __call__
>     await self.app(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\starlette\routing.py", line 580, in __call__
>     await route.handle(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\starlette\routing.py", line 390, in handle
>     await self.app(scope, receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\engineio\async_drivers\asgi.py", line 65, in __call__
>     await self.not_found(receive, send)
>   File "C:\git\dev-env3.9\lib\site-packages\engineio\async_drivers\asgi.py", line 107, in not_found
>     await send({'type': 'http.response.start',
>   File "C:\git\dev-env3.9\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 223, in asgi_send
>     raise RuntimeError(msg % message_type)
> RuntimeError: Expected ASGI message 'websocket.accept' or 'websocket.close', but got 'http.response.start'.
> [2021-07-26 16:12:52,336] DEBUG in websockets.server[server]: server > HTTP/1.1 101 Switching Protocols
> [2021-07-26 16:12:52,336] DEBUG in websockets.server[server]: server > Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', 'AhRSX7l9VHlVjRKmQOVvEtesXkc='), ('Date', 'Mon, 26 Jul 2021 14:12:52 GMT'), ('Server', 'Python/3.9 websockets/9.1')])
> [2021-07-26 16:12:52,337] DEBUG in websockets.protocol[protocol]: server - state = OPEN
> [2021-07-26 16:12:52,337] DEBUG in websockets.protocol[protocol]: server - event = connection_lost(None)
> [2021-07-26 16:12:52,338] DEBUG in websockets.protocol[protocol]: server - state = CLOSED
> [2021-07-26 16:12:52,338] DEBUG in websockets.protocol[protocol]: server x code = 1006, reason = [no reason]
> [2021-07-26 16:12:52,341] DEBUG in websockets.protocol[protocol]: server ! failing CLOSED WebSocket connection with code 1006
> [2021-07-26 16:12:52,342] DEBUG in websockets.protocol[protocol]: server x half-closing TCP connection

Client:

> Attempting WebSocket connection to ws://127.0.0.1:8000/socket/?transport=websocket&EIO=4
> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File "C:\git\dev-env3.9\lib\site-packages\socketio\client.py", line 314, in connect
>     raise exceptions.ConnectionError(exc.args[0]) from None
> socketio.exceptions.ConnectionError: Connection error

**Additional context**
I looked into what ASGIApp gets for information and found out that in asgi.py on line 53 scope['path'] is '/' and self.engineio_path is empty which leads to a comparison of '/'.startswith('//') which is of course not true.
I changed this manually and removed the last / and it worked.

I'm not completely sure if this belongs to here, what is the correct way of handling this? I can't mount SocketIO to / in my app because then my other routes doesnt work anymore. 
My current workaround is that I just do 
`app.mount("/socket", socketio.ASGIApp(socketio_server=sio, socketio_path='/socket'))`
`sio.connect("http://127.0.0.1:8000/", socketio_path='/socket/socket', transports=['websocket'])` 
but that is just strange looking. ;)

**Comment by miguelgrinberg** [comment]
Did you notice that the `ASGIApp` class is also designed to route traffic to a separate application? The way I designed it is to have ASGIApp as the top-level app, then your FastAPI would be receiving any traffic that is not directly related to Socket.IO.

I can probably figure out a way to handle this in the way you are doing it as well, but I can't really guarantee that this is going to work well because I have no idea what happens inside FastAPI for traffic that is directed to a mounted application.

**Comment by tobyX** [comment]
Also the other way around, socketio.ASGIApp is the main and FastAPI the subapp?

My goal is an app which serves REST endpoints like this:
127.0.0.1:5000/v2-sample/service -> REST function
127.0.0.1:5000/v2-sample/socket -> SocketIO
127.0.0.1:5000/v2-sample/openapi.json -> FastAPI Docs
127.0.0.1:5000/v2-sample/<other Rest Functions>

Because of this I would prefer if FastAPI is the main app, as SocketIO should just serve some path below the main path, that feels a bit strange to me. But it works, I just tested it, thanks for the pointer.


I also tested it with your ASGIApp directly and it looks a bit funny when you try it with socketio_path='/'

> [2021-07-26 17:26:15,875] DEBUG in websockets.server[server]: server < GET //?transport=websocket&EIO=4&t=1627313175.8678248 HTTP/1.1
> [2021-07-26 17:26:15,875] DEBUG in websockets.server[server]: server < Headers([('upgrade', 'websocket'), ('host', '127.0.0.1:8000'), ('origin', 'http://127.0.0.1:8000'), ('sec-websocket-key', 'B4PrDwSX5wXA3JkQ+wA6Bw=='), ('sec-websocket-version', '13'), ('connection', 'Upgrade')])
> [2021-07-26 17:26:15,883] DEBUG in asgi[asgi]: scope {'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'scheme': 'ws', 'server': ('127.0.0.1', 8000), 'client': ('127.0.0.1', 58543), 'root_path': '', 'path': '//', 'raw_path': '//', 'query_string': b'transport=websocket&EIO=4&t=1627313175.8678248', 'headers': [(b'upgrade', b'websocket'), (b'host', b'127.0.0.1:8000'), (b'origin', b'http://127.0.0.1:8000'), (b'sec-websocket-key', b'B4PrDwSX5wXA3JkQ+wA6Bw=='), (b'sec-websocket-version', b'13'), (b'connection', b'Upgrade')], 'subprotocols': []} engineio_path //
> INFO:     ('127.0.0.1', 58543) - "WebSocket //" [accepted]
> [2021-07-26 17:26:15,884] INFO in uvicorn.error[websockets_impl]: ('127.0.0.1', 58543) - "WebSocket //" [accepted]

Should it be // instead of just /? I get the impression this was never meant to be run below / directly?

**Comment by miguelgrinberg** [comment]
Two points I want to clarify:

- The `ASGIApp` class has nothing to do with SccketIO, it is just a router app that can direct traffic to three different apps, the Socket.IO app, another ASGI app of your choosing, or a simple static file serving app. The routing that `ASGIApp` uses is fully transparent, so it should be compatible with FastAPI or any other ASGI framework, without the need to make modifications to your URLs (as opposite to the routing done in FastAPI, which does appear to modify the URLs,).
- I do agree with you that putting a Socket.IO app on the root endpoint should work, and will look into adding support for that. It is not something I considered, so there is no code that handles a root URL as a special case. Things may work if you set the Socket.IO path to an empty string, but I"m not sure, I haven't tested this.

**Comment by miguelgrinberg** [comment]
Can I ask you to install the main branch of this repo and tell me if setting the path to `/` now works fine for you?

**Comment by tobyX** [comment]
Thanks for your clarification!
I agree that it is a bit strange that FastAPI/Starlette does this. 
For the records, thats the scope you get from Starlette:
```
scope {'type':                         'websocket',
       'asgi':                         {'version': '3.0', 'spec_version': '2.1'}, 
       'scheme':                       'ws', 
       'server':                       ('172.18.0.6', 5000), 
       'client':                       ('172.18.0.13', 54518), 
       'root_path':                    '/v2-sample/socket', 
       'path':                         '/',
       'raw_path':                     '/v2-sample/socket/',
       'query_string':                 b'transport=websocket&EIO=4&t=1627315972.636018',
       'headers':                      [(b'upgrade', b'websocket'),
                                        (b'host', b'192.168.56.10:8443'),
                                        (b'origin', b'http://192.168.56.10:8443'),
                                        (b'sec-websocket-key', b'XXX'),
                                        (b'sec-websocket-version', b'13'),
                                        (b'connection', b'Upgrade'),
                                        (b'x-forwarded-for', b'172.18.0.1')],
       'subprotocols':                 [],
       'fastapi_astack': < contextlib.AsyncExitStack >,
       'app': < fastapi.applications.FastAPI >,
       'router': < fastapi.routing.APIRouter >,
       'path_params': {},
       'app_root_path': '',
       'endpoint': < socketio.asgi.ASGIApp >
}
```
So the information about the complete path is in there. But I found no way to set path to the same value as root_path.

Thanks for your fast fix, I will test it right away and then give you feedback about it. Thanks!

**Comment by tobyX** [comment]
Works perfectly! Thanks again!
