### ISSUE TITLE
Gevent's async driver is not compatible with the native threading.Thread interface.

### ISSUE THREAD

**Issue by dedoussis** [miguelgrinberg/python-engineio#244]
**Describe the bug**
Within the `engineio.async_drivers.gevent` module, the `Thread` implementation claims to be compatible with the standard library's `Thread` class: https://github.com/miguelgrinberg/python-engineio/blob/main/src/engineio/async_drivers/gevent.py#L13

However this does not seem to be the case.
The `engineio.async_drivers.gevent.Thread` class subclasses the Greenlet class instead of the [gevent.threading.Thread](http://www.gevent.org/api/gevent.threading.html#gevent.threading.Thread) class.

**To Reproduce**
```
Python 3.9.0 (default, Apr 22 2021, 08:56:23) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from engineio.async_drivers.gevent import Thread
>>> Thread(lambda: None, daemon=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'daemon'
```
**Expected behavior**
Passing the `daemon` kwarg to the Thread instance constructor should not raise a `TypeError`.

**Comment by dedoussis** [comment]
Will be raising a PR to address this, if that's alright

**Comment by miguelgrinberg** [comment]
Why is this an issue? The `Thread` class is used internally. It does not need to fully compatible with Python's `Thread` class.

**Comment by dedoussis** [comment]
Bringing the PR discussion into this issue, so that we have a single thread to focus on.

> As stated in the issue, I don't really see what is the improvement this change brings to the project. Did you have any problems with the current implementation?

I started looking into this implementation because I attempted to use the [flask_socketio.SocketIO.start_background_task](https://github.com/miguelgrinberg/Flask-SocketIO/blob/main/src/flask_socketio/__init__.py#L682) method to start a daemonised thread. This method ultimately calls the [engineio.Server.start_background_task](https://github.com/miguelgrinberg/python-engineio/blob/main/src/engineio/server.py#L445) method which only passes the `target`, `args` and `kwargs` arguments to the constructor that implements the `threading.Thread` interface, and thus it does not allow the construction of a daemonic thread (neither groupped or named). Thus, I attempted to subclass `flask_socketio.SocketIO` and re-implement the `start_background_task` method as follows:

```python
    def start_background_task(
        self, target: Callable, *args, **kwargs
    ) -> threading.Thread:
        """
        Similar to :meth:`flask_socketio.SocketIO.start_background_task` 
        with the only difference that the thread created is daemonic.
        """
        th: threading.Thread = self.server.eio._async["thread"](
            target=target, args=args, kwargs=kwargs, daemon=True
        )
        th.start()
        return th
```
As I am using `gevent` as the `async_mode` this raised a `TypeError`.

I do understand that I started playing with the private parts of the EngineIO API, since `_async` is not a public method. However, the documentation of `start_background_task`, which is a public method, claims that it returns an object that implements the `threading.Threading` interface, which is a false statement:
```
Python 3.9.0 (default, Apr 22 2021, 08:56:23) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from engineio.async_drivers.gevent import Thread
>>> t = Thread(target=lambda: None)
>>> t.daemon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Thread' object has no attribute 'daemon'
```
The 2 options I see going forward are:
1. Make the returned object to be completely compatible with the `threading.Thread` interface
2. Correct the documentation of the `start_background_task` method, and declare the parts of the interface that are universally supported.

For me, option 1 is preferred, since gevent has implemented a utility for this exact purpose: http://www.gevent.org/api/gevent.threading.html#gevent.threading.Thread

**Comment by dedoussis** [comment]
In the case of going forward with option 2, I would then like to implement some functionality similar to `start_background_task` but with all arguments passed to the `threading.Thread` constructor (rather than just `target`, `args` and `kwargs`. The current signature of `engineio.Server.start_background_task` does not allow this change in a backwards compatible manner, so we will have to introduce a new method.

If you're interested in further context as to why I need this kind of functionality, here's the PR that I'm working on: https://github.com/dedoussis/asynction/pull/65/files#diff-2e7462c74d3d254c1f273d7bb6f051b0a892c34abbe400f6a68e9af504cfc331R284

**Comment by miguelgrinberg** [comment]
@dedoussis I'm confused, because when you use gevent (or eventlet, for that matter) the concepts a threads, or daemon threads do not exist. These are greenlets that have a `Thread` interface. I haven't looked at the implementation of the `Thread` class in gevent, but I bet you they just ignore the `daemon` argument, because if you think about it, what are they going to do with it? There are no threads in a gevent program.

So all this effort is going to just let you pass the argument, so that it is then ignored.

**Comment by dedoussis** [comment]
@miguelgrinberg What I'm building in this case is a library (which is a thin wrapper on top of Flask-SocketIO), rather than a service. This library needs to start  a "background task" with a daemon-like behaviour and needs to be able to do that in all possible async modes. Thus, I'm looking for an abstract solution that works for both green and traditional threads.

You are correct in saying that Greenlets do not have this `daemon` argument , however they could have daemoninc or non-daemonic behaviour. I'm not aware of how this is implemented but I observed that if you create a greenlet using the `gevent.threading.Thread` class and set `daemon` to `False`, the greenlet will behave as a non-daemonic thread (in the sense that it is not going to terminate if the parent greenlet exits). By default, gevent greenlets have daemon-like behaviour.

With the current state of things, my library works with Greenlets (that behave as daemons by default), but does not work with Threads (that are non-daemons by default). So yes, the argument is essentially going to be ignored in the greenlet scenario, but is going to be used in the threading scenario.

**Comment by dedoussis** [comment]
To give you a more concrete example, with the current state of things I have to resort to a hack like this:
```python
    def start_background_task(
        self, target: Callable, *args, **kwargs
    ) -> threading.Thread:
        if self.async_mode in ["gevent", "gevent_uwsgi"]:
            th = self.server.eio._async["thread"](
                target=target, args=args, kwargs=kwargs
            )
        else:
            th = self.server.eio._async["thread"](
                target=target, args=args, kwargs=kwargs, daemon=True
            )

        th.start()
        return th
```
to make sure that the library is compatible with both threading and greenlet async modes.

**Comment by miguelgrinberg** [comment]
> I do understand that I started playing with the private parts of the EngineIO API, since _async is not a public member. However, the documentation of start_background_task, which is a public method, claims that it returns an object that implements the threading.Thread interface, which is a false statement:

You are using private parts of the package, which I'm under no obligation to support. The documentation does not say that this package provides a general-purpose `Thread` class that you can use to create your own threads. It just says that the `start_background_task()` function returns such an object. There is a difference there, but still, I agree that this isn't entirely accurate because the object returned by this function is "close" to being compatible with Python's `Thread` class, but not 100% compatible. Making this clear in the documentation would be a good idea.

I'm not really happy with this change because if you start using my internal `Thread` class I would be forced to continue supporting it. And what does this package get in return? Nothing. You are not helping this package do anything better, this change just opens an internal backdoor so that you can access some functionality you need for your project.

My suggestion is that if the `start_background_task()` function offered by this package is insufficient for your needs, you build something different, without relying on the internals of this package, which could change and break your project.
