### ISSUE TITLE
Incompatible with Sanic 21.9.1

### ISSUE THREAD

**Issue by wtfuzz** [miguelgrinberg/python-engineio#251]
**Describe the bug**
It seems engineio is incompatible with Sanic 21.9.1

```
[2021-10-06 18:04:25 -0700] [349517] [ERROR] Exception occurred while handling uri: 'http://localhost:8080/socket.io/?transport=polling&EIO=4&t=1633568665.1407533'
Traceback (most recent call last):
  File "/home/fuzz/silvertip/silvertip-venv/lib/python3.8/site-packages/sanic/signals.py", line 73, in get
    group, param_basket = self.find_route(
  File "", line 68, in find_route
sanic_routing.exceptions.NotFound: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fuzz/silvertip/silvertip-venv/lib/python3.8/site-packages/sanic/http.py", line 141, in http1
    await self.protocol.request_handler(self.request)
  File "/home/fuzz/silvertip/silvertip-venv/lib/python3.8/site-packages/sanic_plugin_toolkit/realm.py", line 550, in _handle_request_21_03
    _ = await real_handle(request)
  File "/home/fuzz/silvertip/silvertip-venv/lib/python3.8/site-packages/sanic/app.py", line 769, in handle_request
    await self.dispatch(
  File "/home/fuzz/silvertip/silvertip-venv/lib/python3.8/site-packages/sanic/signals.py", line 163, in dispatch
    return await dispatch
  File "/home/fuzz/silvertip/silvertip-venv/lib/python3.8/site-packages/sanic/signals.py", line 114, in _dispatch
    raise e
  File "/home/fuzz/silvertip/silvertip-venv/lib/python3.8/site-packages/sanic/signals.py", line 111, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/home/fuzz/silvertip/silvertip-venv/lib/python3.8/site-packages/sanic/signals.py", line 86, in get
    raise NotFound(message % tuple(terms))
sanic_routing.exceptions.NotFound: Could not find signal http.lifecycle.handle
```

**To Reproduce**
Upgrade Sanic to 21.9.1 and attempt to connect a SocketIO/EngineIO client

**Expected behavior**
Successful connection

**Comment by cnicodeme** [comment]
Note that on my case, this yield another error:

> Traceback (most recent call last):
>   File "/home/user/www/project/env/lib64/python3.9/site-packages/sanic/server/protocols/websocket_protocol.py", line 120, in websocket_handshake
>     subprotocols = list(subprotocols)
>   File "/usr/lib64/python3.9/typing.py", line 268, in inner
>     return func(*args, **kwds)
>   File "/usr/lib64/python3.9/typing.py", line 750, in __getitem__
>     params = tuple(_type_check(p, msg) for p in params)
>   File "/usr/lib64/python3.9/typing.py", line 750, in <genexpr>
>     params = tuple(_type_check(p, msg) for p in params)
>   File "/usr/lib64/python3.9/typing.py", line 157, in _type_check
>     raise TypeError(f"{msg} Got {arg!r:.100}.")
> TypeError: Parameters to generic types must be types. Got 0.

But it's related to a bug at Sanic (`async def websocket_handshake(self, request, subprotocols=Optional[Sequence[str]]):` instead of `async def websocket_handshake(self, request, subprotocols:Optional[Sequence[str]] = None):`)

I'm going to open an Issue at Sanic ;)

**Comment by cnicodeme** [comment]
The above code was using `packaging` package, which is not installed by default (it isn't on my setup), so you'll need to add it to the required package.

If you don't want, you can do the following, which works fine .... As long as Sanic respect the Major.Minor.Patch versioning with integers only (no "alpha").

```
try:  # pragma: no cover
    from sanic import __version__ as sanic_version
    from sanic.response import HTTPResponse

    sanic_version = tuple([int(x) for x in sanic_version.split('.')])
    if sanic_version > (21, 6, 2):
	from sanic.server.protocols.websocket_protocol import WebSocketProtocol
    else:
        from sanic.websocket import WebSocketProtocol
except ImportError:
    HTTPResponse = None
    WebSocketProtocol = None
```

 * The packaging code provides a future-proof way of testing but requires the `packaging` module
 * The above code removes the needs for `packaging` module, but might break if Sanic decides to add leter to their version.

**Comment by cnicodeme** [comment]
Looking at Sanic Policy on code versioning, it should be fine : https://sanicframework.org/en/org/policies.html

> Sanic uses calendar versioning (opens new window), aka "calver". To be more specific, the pattern follows:
> 
> YY.MM.MICRO
> 
> Generally, versions are referred to in their YY.MM form. The MICRO number indicates an incremental patch version, starting at 0.

**Comment by cnicodeme** [comment]
And if you want to be absolutely sure it won't break in the future, you can catch the code part that generates the tuple for any exception, and set a default value to a higher version:

```
try:  # pragma: no cover
    from sanic import __version__ as sanic_version
    from sanic.response import HTTPResponse

    try:
        sanic_version = tuple([int(x) for x in sanic_version.split('.')])
    except Exception:
        sanic_version = (21, 9, 1)  # Current version as of 2021-11-15

    if sanic_version > (21, 6, 2):
	from sanic.server.protocols.websocket_protocol import WebSocketProtocol
    else:
        from sanic.websocket import WebSocketProtocol
except ImportError:
    HTTPResponse = None
    WebSocketProtocol = None
```

I checked their older version and none of them have a char in their version.

**Comment by 13g10n** [comment]
Hi @miguelgrinberg 
Thanks for your work and happy new 2022!

Could you please check #265 and let me know if you have any additional thoughts. It is based on problems I have faced locally in my pet project and this issue. I have investigated and tested the solution with different `sanic` versions and it looks pretty good and stable.

Thanks,
Ivan.

**Comment by m-vdb** [comment]
nice! thanks for fixing the issue. @miguelgrinberg would it be possible to get a pypi release for this fix?

**Comment by miguelgrinberg** [comment]
This is now released to PyPI.

**Comment by m-vdb** [comment]
Awesome! thanks a lot 🙏🏻
