### ISSUE TITLE
Add timeout feature for write_loop on the client side

### ISSUE THREAD

**Issue by its-mohnish** [miguelgrinberg/python-engineio#263]
**Is your feature request related to a problem? Please describe.**
I am working with a server which pings me only when someone does an action on the website. Since, its not necessary for a client to do an action continuosly, the intervals between each ping could be infinite. Now, whenever the queue is empty for more than the timeout period, the write loop task is exited leading to a disconnection.

**Describe the solution you'd like**
Can you please add a feature - timeout, so that we can set the timeout to None. This would make the queue wait for a packet indefinitely and hence, help with this issue

**Describe alternatives you've considered**

**Logs**
```
Attempting polling connection to https://server.com/socket.io/?token=someToken&transport=polling&EIO=4
Polling connection accepted with {'sid': 'bk197sdhdYAv76H-C3vZ', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 20000}
Engine.IO connection established
Sending packet MESSAGE data 0
Attempting WebSocket upgrade to wss://server.com/socket.io/?token=someToken&transport=websocket&EIO=4
WebSocket upgrade was successful
Received packet MESSAGE data 0{"sid":"V1XD_k2voR_o_RUAC3vt"}
Namespace / is connected
Received packet MESSAGE data 2 xxxxxxxxxxxxxxxxxxxxxxx
Received event "data" [/]
Received packet PING data
Sending packet PONG data
Received packet PING data
Sending packet PONG data
packet queue is empty, aborting
Received packet PING data
Exiting write loop task
Sending packet PONG data
Waiting for write loop task to end
Engine.IO connection dropped
```
**Additional context**

**Comment by miguelgrinberg** [comment]
Wouldn't it make more sense for you to request the developer of the server to implement the Socket.IO protocol correctly? Why would you want the client to violate the protocol instead?
