### ISSUE TITLE
Regex CORs

### ISSUE THREAD

**Issue by hmajid2301** [miguelgrinberg/python-engineio#264]
**Is your feature request related to a problem? Please describe.**

Would it be possible to add regex CORs as an option, so we can support wildcard domains ? 

**Describe the solution you'd like**

Perhaps you could specify another argument, something like so ? 

`socketio.AsyncServer(async_mode="asgi", regex_cors_allowed_origins=["http://localhost*:3000"])`

**Describe alternatives you've considered**

**Logs**

**Additional context**

**Comment by miguelgrinberg** [comment]
The CORS specification does not support origins given as regular expressions.

**Comment by hmajid2301** [comment]
Yeh sure, I know its not the same but FastAPI have their own implementation to support RegexCORs is there any appetite for this ? Or is there another way I can support wildcard domains.

Thanks

**Comment by miguelgrinberg** [comment]
How about this. Let's say the `cors_allowed_origins` option is extended to support a callable in addition to a string. When using this option, your function will be called to decide if an origin is allowed or not.

**Comment by hmajid2301** [comment]
yeh that sounds like a nice elegant "workaround". Thanks Miguel
