### ISSUE TITLE
Receiving empty non-binary packets during connection establishment result in a crash

### ISSUE THREAD

**Issue by sirkrypt0** [miguelgrinberg/python-engineio#269]
**Describe the bug**

Receiving empty non-binary packets during connection establishment result in a crash. This is due to a `Packet` with an `encoded_packet = ''` results in an uncaught `IndexError`.

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/socketio/client.py", line 660, in _handle_reconnect
    self.connect(self.connection_url,
  File "/usr/local/lib/python3.9/site-packages/socketio/client.py", line 331, in connect
    self.eio.connect(real_url, headers=real_headers,
  File "/usr/local/lib/python3.9/site-packages/engineio/client.py", line 185, in connect
    return getattr(self, '_connect_' + self.transports[0])(
  File "/usr/local/lib/python3.9/site-packages/engineio/client.py", line 324, in _connect_polling
    if self._connect_websocket(url, headers, engineio_path):
  File "/usr/local/lib/python3.9/site-packages/engineio/client.py", line 444, in _connect_websocket
    pkt = packet.Packet(encoded_packet=p)
  File "/usr/local/lib/python3.9/site-packages/engineio/packet.py", line 27, in __init__
    self.decode(encoded_packet)
  File "/usr/local/lib/python3.9/site-packages/engineio/packet.py", line 51, in decode
    b64 = not self.binary and encoded_packet[0] == 'b'
IndexError: string index out of range
```

**To Reproduce**

When receiving an empty packet which is not bytes (e.g. `''`), the Packet class tries to decode this (it did not previous the mentioned commit) and throws an exception as it cannot read the first byte (which is supposed to contain the packet type).

This behavior can occur when establishing a WebSocket connection. In our case, it appeared after the PING packet has been sent and a PONG packet is expected to be received.

https://github.com/miguelgrinberg/python-engineio/blob/06480be268852ffc96793ef52213ad598b85fa69/src/engineio/client.py#L437-L444

Somehow, the packet got not received properly and the `websocket-clients` library `recv` function might return an empty string (see [source](https://github.com/websocket-client/websocket-client/blob/d7aa5c9c244e227041764c63949d3121f84145ac/websocket/_core.py#L353-L368)).
In that case, the empty packet (`''`) is decoded which causes the exception to be raised.

**Expected behavior**

An empty non-binary `encoded_packet` is not decoded and no exception is raised.

**Additional information**

The commit bcd1a42f86aad12460b6eb836a5c317db55cba77 introduced the feature to support binary packets with zero length. 
However, the change introduced this bug here.

**Comment by miguelgrinberg** [comment]
I don't understand how this can happen. An empty binary packet is perfectly legal, because binary packets are attachments that are sent after the main packet. An empty text packet is really illegal, there is nothing that can be done when the main packet doesn't provide at least a packet type.

Also, the websocket-client package returns an empty string when the packet is not text or binary. The Socket.IO protocol does not support anything that is not either text or binary. So basically you have a client that is sending illegal WebSocket frames. The correct way to handle this would be to crash and close the connection as invalid, though in a more graceful way than it currently fails for sure.

Or am I missing something? How can this be a valid use case?

**Comment by sirkrypt0** [comment]
I'm not entirely sure how this happened in the first place. The issue just randomly appeared (and has only appeared once in the past 4 months we are using this), seemingly while the `socketio` client was trying to reconnect to the server and crashed.
For context, we use the [`nestjs/websockets`](https://www.npmjs.com/package/@nestjs/websockets) library on the server side.

**Comment by miguelgrinberg** [comment]
As far as I know, nestjs/websockets is a WebSocket client, which is incompatible with this package. You must be using a Socket.IO client.

**Comment by sirkrypt0** [comment]
According to their [documentation](https://docs.nestjs.com/websockets/gateways) they support both, `websockets` and `socket.io`. With `socket.io` they use the official [socket.io](https://github.com/socketio/socket.io) library. See also the official example [here](https://github.com/nestjs/nest/tree/master/sample/02-gateways).
