### ISSUE TITLE
Disconnect in AsyncClient causes error: Unclosed client session

### ISSUE THREAD

**Issue by pawalther** [miguelgrinberg/python-engineio#272]
Hi,

I'm using socketio/engineio for a simple websocket chat client. A dummy implementation is as follows:

<details><summary>Dummy implementation</summary>
<p>

```python
import asyncio  
import socketio

from prompt_toolkit import PromptSession
from prompt_toolkit.patch_stdout import patch_stdout

sio = socketio.AsyncClient()

@sio.on('chat')
def message(data):
  print(data)

async def main_loop():
  session = PromptSession(erase_when_done=True)
  while True:
    message = await session.prompt_async(' > ')
    if message == 'quit':
       break
    else:
      await sio.emit('chat', {'name':'name', 'text': message})
  await sio.disconnect()

async def main():
  with patch_stdout():
    await asyncio.gather(
            main_loop(),
            sio.connect(URL),
    )   

if __name__ == '__main__':
  asyncio.run(main())
```

</p>
</details>

Disconnecting the client produces the following error message:
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe4ca605e50>

I've traced the origin of this message to the deconstructor of the AsyncClient here: https://github.com/miguelgrinberg/python-engineio/blob/06480be268852ffc96793ef52213ad598b85fa69/src/engineio/asyncio_client.py#L194
Here, the HTTP session is not closed because the asyncio.get_event_loop() fails with an RuntimeError due to the fact that there is no current asyncio loop.

Am I using the AsyncClient wrongly here?

If not, the error could be fixed by not swallowing the RuntimeError silently. So instead of
```python
try:
    ...
except:
    pass
```
something like this works as expected and correctly closes the aiohttp client session
```python
try:
    ...
except RuntimeError as e:
    if 'There is no current event loop in thread' in e.args[0]:
        asyncio.run(self.http.close())
```

Thank you very much! :-)

**Comment by miguelgrinberg** [comment]
The problem is that because the particular way you are waiting, the `sio` object continues to be active past the point where the loop is gone, so at this point the only way to do a clean destruction is to hack a new loop, like you did. A better approach would be to not let the loop go away until the Socket.IO client is fully closed.

For example, does it fail if you add this at the end of the `main()` function?

```python
await sio.wait()
```

**Comment by pawalther** [comment]
Thank you for your response :-)

Unfortunately, your suggested solution does not fix the problem.

Might there be another way to keep to loop alive?

**Comment by miguelgrinberg** [comment]
@pawalther please try the main branch on this repo and let me know if the problem is addressed.

**Comment by pawalther** [comment]
Works perfectly in my case :-)

Thank you very much for the quick fix!
