### ISSUE TITLE
Python 3.6 does not support asyncio.get_event_loop().add_signal_handler and async_client.py spams about it on every connect attempt

### ISSUE THREAD

**Issue by bialix** [miguelgrinberg/python-engineio#276]
``engineio/asyncio_client.py`` has the following code at the very start of ``connect``:

```
        global async_signal_handler_set
        if self.handle_sigint and not async_signal_handler_set and \
                threading.current_thread() == threading.main_thread():
            try:
                asyncio.get_event_loop().add_signal_handler(
                    signal.SIGINT, async_signal_handler)
                async_signal_handler_set = True
            except NotImplementedError:  # pragma: no cover
                self.logger.warning('Signal handler is unsupported')
```

The problem here is that variable ``async_signal_handler_set`` will never be set to True in this case and logger is spamming my logs with useless warning. 

May I suggest to rename ``async_signal_handler_set`` to ``async_signal_handler_once`` and set it regardless of exception raised to avoid it triggered next time? I can make PR if you agree.

**Comment by miguelgrinberg** [comment]
Yes, your suggestion makes sense. Thanks.

**Comment by miguelgrinberg** [comment]
@bialix I believe there is no support for signal handlers in the Windows event loop, so there is currently no way to exit cleanly on that platform.

**Comment by bialix** [comment]
Yep, I think you're right.

So, should I compose a patch or you do it yourself?

**Comment by bialix** [comment]
OK, that's definitely problem with your signal_handler.
Once you set it - your handler overrides my own SIGINT handler. And I'm not sure it's desired side-effect.

**Comment by miguelgrinberg** [comment]
I'm going to close this issue, since you have now moved the discussion to python-engineio/issues/277.

**Comment by bialix** [comment]
#277 is about disconnect method. This issue is about spaming with warnings. I don't understand, but it's up to you to close issues, that's your project.

**Comment by miguelgrinberg** [comment]
I settled the discussion on the multiple attempts to set a signal in the 2nd message in this issue:

> Yes, your suggestion makes sense. Thanks. If you create the PR I'll review and merge.

Everything else in this issue is unrelated to that problem. In any case, I just submitted the fix for the original issue you reported here. Now the signal will be set the first time you connect only.
