### ISSUE TITLE
engineio.asyncio_client.disconnect should always close underlying aiohttp object

### ISSUE THREAD

**Issue by bialix** [miguelgrinberg/python-engineio#277]
This is from discussion https://github.com/miguelgrinberg/python-socketio/discussions/927

I think I found the bug in your async_client.

Method ``async def disconnect(self, abort=False):`` executes ``await self.http.close()`` only if object is connected. Which is clearly wrong.
Simple doing this regardless of the connected state fixes the problem:

```
        if self.http and not self.http.closed:  # pragma: no cover
            await self.http.close()
```

Also I think you should document your inner side effect of attaching your own SIGINT handler which overrides anything user attached before running AsyncClient.

**Comment by miguelgrinberg** [comment]
Can I ask you to please stay on a single issue or discussion? There's three open conversations right now from you, and you are repeating/copying the same details on all of them. There is no point to this.

> Method async def disconnect(self, abort=False): executes await self.http.close() only if object is connected. Which is clearly wrong.

What is it clearly wrong? Why would you the `disconnect()` call do anything if you are not connected anymore?

**Comment by bialix** [comment]
Miguel, I'm a bit frustrated right now. I spend entire working day to hunt the problem with socketio AsyncClient just to discover there are 3 problems in engineio, well maybe only 2.5 problems and +1 problem in asyncio.

I've carefully extracted the code from my bigger working project into small example - all you need is to clone it and run on your  Python, you even don't need corresponding server to reproduce.

Please point me into the right place where I can explain all 3 problems I found with engineio.async_client.

About underlying ``self.http`` object. My initial question was about properly terminate AsyncClient of socketio library but it turned out the problem in engineio. I don't understand where should I put my report.

OK. Just about why I said "clearly wrong". Just because your code said that.

In engineio.async_client __del__ method there are code which triggered my initial question about aiohttp.ClientSession hasn't been closed properly. Your code checks ``if self.http and not self.http.closed:`` and this evaluated to True. The problem with destructor is that it called when it's already too late in my case - the event loop was stopped closed and destroyed I think.

So, in your async client object there are many states:
1. object created but not trying to connect yet
2. object trying to connect
3. object connected
4. client explicitly call disconnect (the only proper way to close self.http) when it was connected (or via signal handler)
5. client was connected but server disappear and connection has been broken - your code tries to reconnect
6. client unable to connect and socketio.exceptions.ConnectionError raised

So, I found by testing and you can reproduce it with my examples - engineio's disconnect method right now only closes underlying aiohttp client session in the case of 3 and 4. I rather avoid to check all your code for all possible states and whether it closed self.http or not. I'm already full.

About spam with warnings - if you say your code is not supported Windows - well I will live with that.

About signal handler - my client_example2.py clearly shows that my own signal handler is *not* called. And when I prevent your code to set your own signal handler - it "fixes" my signal handler. What should I say here? Let's blame asyncio then. I'm just quite frustrated with all related to asyncio in Python already.

Just to be clear - I need my own shutdown procedure because I'm working on a bigger project where your socketio is only part of the bigger picture. I've spent a lot of time to understand what is the correct way to shutdown asyncio-based application and found that series of articles "asyncio": we did it wrong" and explanation about shutdown: https://www.roguelynn.com/words/asyncio-graceful-shutdowns/ and I should say I found another gist on github which is even better than code in the article above. This is all in my client-example2.py.

Once I fixed "problem" with your disconnect and prevent your code to set signal handler - everything started to work properly.

So, please forgive me if I wrongly blame your code. I just have several problems and now I need to find the way to ship patched version of your code with my app which is not trivial question.

**Comment by miguelgrinberg** [comment]
First of all, you have a very easy way to incorporate this solution, without changing anything in this project:

```python
class MyAsyncClient(socketio.AsyncClient):
    async def disconnect(self, *args, **kwargs):
        await super().disconnect(*args, **kwargs)
        if self.eio.http and not self.eio.http.closed:
            await self.eio.http.close()
```

Then use `MyAsyncClient` as your client. This should work for you without updates to the socketio and engineio packages.

The issue I have with this solution is that `disconnect()` is not a cleanup function, it is supposed to be a function that disconnects a connected client. Your client is not connected, so there is nothing to disconnect. I don't want to influence the design of this client to cover for annoyances in other packages.

A more likely option that I need to explore is adding a cleanup method where clients can release resources. This sounds like a more appropriate way to close an open HTTP session when the application will not use it anymore.
