### ISSUE TITLE
Access a socket's last PONG

### ISSUE THREAD

**Issue by wyattisimo** [miguelgrinberg/python-engineio#282]
**Is your feature request related to a problem? Please describe.**
We have a Flask service that facilitates communication between REST clients and SocketIO clients. We're using flask-restful and flask-socketio.

We have a use case where the service needs to return the "last heartbeat" timestamp of a SocketIO client upon request from a REST client.

**Describe the solution you'd like**
We would like to just leverage SocketIO's built-in heartbeat mechanism and get the time of the client's last PONG.

Couple of issues:
* `Server#_get_socket()` is undocumented/private, and therefore could technically be changed without the need to bump the package major version, which could break our implementation.
* `Socket` instances do not currently maintain `last_pong` timestamps.

I think a good solution would be to make `Server#_get_socket()` public and implement a `Socket#last_pong` timestamp. This would also mean including the `Socket` class in the docs.

**Describe alternatives you've considered**
Get the socket via `Server#_get_socket()` and just use `Socket#last_ping` as an approximation.

**Comment by miguelgrinberg** [comment]
I prefer not to add features that are unlikely to be useful for the majority of users. I have received a few requests for unusual features and what I was thinking is to make the  `socketio.Server._engineio_server_class` public and documented. This would allow you to create subclasses of `socketio.Server` and `engineio.Server`, and override the handling of incoming packets to add the custom logic that you need to track ping/pongs.

Would that work?

**Comment by wyattisimo** [comment]
That's an interesting idea. Would you also be open to making `engineio.Socket` public and documented?

I'm not seeing a super clean way to override the handling of incoming packets with a subclass of `socketio.Server` or `engineio.Server`. But if I could subclass `engineio.Socket`, then maybe I could do something like this:

```python
class MySocket(engineio.Socket):

    def __init__(self, server, sid):
        self.last_pong = None
        super().__init__(server, sid)

    def receive(self, pkt):
        if pkt.packet_type == packet.PONG:
            self.last_pong = time.time()
        super().receive(pkt)
```

**Comment by miguelgrinberg** [comment]
Hmm, okay, maybe my idea wasn't so great after all. The `Socket` class is going to remain internal and undocumented. You will need take a bit of risk there if you decide to override its behavior.

**Comment by miguelgrinberg** [comment]
Closing, as I will not be implementing this for the time being.
