### ISSUE TITLE
Invalid session

### ISSUE THREAD

**Issue by charyorde** [miguelgrinberg/python-engineio#29]
Can you please explain what could be the possible reason for this:
```
WARNING ? engineio: Invalid session aac0657cb8a44b1dbc02738e33749f9e
```
Using `gevent`. Transport is `polling`

**Comment by charyorde** [comment]
More server debug:

```
engineio: 8fd756b7159c48fc9332d6058de773d2: Sending packet OPEN data {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': [], 'sid': '8fd756b7159c48fc9332d6058de773d2'}
INFO ? engineio: 8fd756b7159c48fc9332d6058de773d2: Sending packet MESSAGE data 0
INFO ? werkzeug: 127.0.0.1 - - "GET /socket.io/?EIO=3&transport=polling&t=LSzRpPJ HTTP/1.0" 200 -
WARNING ? engineio: Invalid session 8fd756b7159c48fc9332d6058de773d2
INFO ? werkzeug: 127.0.0.1 - -  "GET /socket.io/?EIO=3&transport=polling&t=LSzRpaP&sid=8fd756b7159c48fc9332d6058de773d2 HTTP/1.0" 400 -
werkzeug: 127.0.0.1 - -  "POST /socket.io/?EIO=3&transport=polling&t=LSzRpnf&sid=8fd756b7159c48fc9332d6058de773d2 HTTP/1.0" 400 -

**Comment by miguelgrinberg** [comment]
The invalid session indicates that the server process received a Socket.IO request with a session it does not know about.

Possible causes I can think of:

- you have multiple gevent servers. If server #1 creates the session, but then server #2 receives a subsequent request you will get this message. The solution is to either ensure multiple servers are handled with sticky sessions, or else use a single server.
- your log does not show the times of each message. A session is removed after 60 seconds of inactivity (the value of the "pingTimeout" argument returned in the open packet).

**Comment by charyorde** [comment]
Thank you for the swift response. 

I think it's the case of option 1. However, I want to maintain a single server. After some adjustments, the logs now looks like this (without the invalid session error):
```
('SOCKET CONNECTED ', '812fd7b85f47440f986596bdbf8fb9e3')
2016-09-18 15:09:07,291 17879 INFO ? werkzeug: 127.0.0.1 - - [18/Sep/2016 15:09:07] "GET /socket.io/?EIO=3&transport=polling&t=LSzr_qU HTTP/1.0
" 200 -
2016-09-18 15:09:07,292 17879 INFO ? openerp.service.server: Worker (17879) exiting. request_count: 1, registry count: 1.
2016-09-18 15:09:07,315 17877 INFO ? werkzeug: 127.0.0.1 - - [18/Sep/2016 15:09:07] "GET /socket.io/?EIO=3&transport=polling&t=LSzr_qw&sid=812f
d7b85f47440f986596bdbf8fb9e3 HTTP/1.0" 400 -
2016-09-18 15:09:07,316 17877 INFO ? openerp.service.server: Worker (17877) exiting. request_count: 1, registry count: 1.
2016-09-18 15:09:07,340 17878 INFO ? werkzeug: 127.0.0.1 - - [18/Sep/2016 15:09:07] "POST /socket.io/?EIO=3&transport=polling&t=LSzr_rL&sid=812fd7b85f47440f986596bdbf8fb9e3 HTTP/1.0" 400 -

('SOCKET CONNECTED ', '897f54cb80de4bf4861406c727ecc563')
2016-09-18 15:09:08,524 17887 INFO ? werkzeug: 127.0.0.1 - - [18/Sep/2016 15:09:08] "GET /socket.io/?EIO=3&transport=polling&t=LSzs07m HTTP/1.0" 200 -
2016-09-18 15:09:08,525 17887 INFO ? openerp.service.server: Worker (17887) exiting. request_count: 1, registry count: 1.
2016-09-18 15:09:08,555 17889 INFO ? werkzeug: 127.0.0.1 - - [18/Sep/2016 15:09:08] "GET /socket.io/?EIO=3&transport=polling&t=LSzs08F&sid=897f54cb80de4bf4861406c727ecc563 HTTP/1.0" 400 -
2016-09-18 15:09:08,556 17889 INFO ? openerp.service.server: Worker (17889) exiting. request_count: 1, registry count: 1.
2016-09-18 15:09:08,893 17894 INFO openerp.service.server: Worker WorkerHTTP (17894) alive
2016-09-18 15:09:08,899 17894 INFO openerp.service.server: Worker (17894) virtual memory limit (2653151232) reached.
2016-09-18 15:09:08,904 17894 INFO ? werkzeug: 127.0.0.1 - - [18/Sep/2016 15:09:08] "POST /socket.io/?EIO=3&transport=polling&t=LSzs090&sid=897f54cb80de4bf4861406c727ecc563 HTTP/1.0" 400 -
```
The server sent `200` status on every new connection(poll) and `400` afterwards. Is this a normal behaviour?

**Comment by miguelgrinberg** [comment]
No, that is not normal, there should not be 400 errors in the log. Also, a given client should continue to use the same session id through the life of the connection.

Also, it seems you dropped the engineio logging you had in the previous log snippet. I think there are still engineio errors that you are not seeing.

**Comment by charyorde** [comment]
Okay. I switched to a standalone Flask-gevent app, but I want to use it with a Messaging Queue backend so that I can get the messages from an external app. I have below code at the moment:
```
import socketio

from flask import Flask

from kombu import Connection, Exchange
from kombu.pools import producers
from kombu import Producer

app = Flask(__name__)

mgr = socketio.KombuManager('amqp://guest:guest@localhost:5672')
sio = socketio.Server(client_manager=mgr)

@sio.on('connect')
def connect(sid, environ):
    print('connect ', sid)

@sio.on('livebet')
def produce(sid, message):
    #sio.emit('livebet', message)
    print("new livebet %r" % message)

import gevent
from gevent.wsgi import WSGIServer
app = socketio.Middleware(sio, app)

gevent.spawn()
interface = '0.0.0.0'
port = 5000
httpd = WSGIServer((interface, port), app)
print('Evented Service (longpolling) running on %s:%s', interface, port)
try:
    httpd.serve_forever()
except:
    print("Evented Service (longpolling): uncaught error during main loop")
    raise
```
Does this combination make sense? I mean can I use Flask-socketio-gevent + Messaging Queue backend. Shouldn't it be Flask-socketio + Messaging Queue or Flask-socketio-gevent?

Let's say I go with `Flask-socketio + Messaging Queue`, do I still need this line `app = socketio.Middleware(sio, app) `?

When a message comes from a client, does it mean that it goes directly into the Messaging Queue and I can retrieve it on my standalone socketio server like this:
```
@sio.on('livebet')
def produce(sid, message):
    #sio.emit('livebet', message)
    print("new livebet %r" % message)
```
and a `sio.emit()` sends it back to the Messaging Queue for connected consumers to process?

**Comment by charyorde** [comment]
Okay. When I added below code, I could retrieve messages from the messaging queue directly over sio.
```
import gevent.monkey
gevent.monkey.patch_all()
```

**Comment by ravimaharjan** [comment]
Hi miguelgrinberg,
I have multiple gunicorn workers running. And for the first reason you mentioned, I am getting this error. Is it possible to use sticky sessions with Gunicorn. The link below however, says it does not support.
https://flask-socketio.readthedocs.io/en/latest/

**Comment by miguelgrinberg** [comment]
No, gunicorn does not support sticky sessions. If you need to run multiple servers, then your only option is to run them as separate gunicorn processes, using a message queue so that these processes can collaborate, and finally putting nginx or other load balancer in front of the workers. The load balancer will have to be configured for sticky sessions for this to work.

**Comment by ravimaharjan** [comment]
I have the config file for the Gunicorn as given below. 
`bind = "127.0.0.1:18000"
workers = min(4, multiprocessing.cpu_count() * 2 + 1)
preload = True
worker_class = "gevent"
loglevel = "warning"`

When you said separate gunicorn processes, I guess it is not the Gunicorn workers i.e. -w parameters. I have read your comments on other posts where you said multiple gunicorn workers are not necessary because greenlets handle it. If it is so, when do we need the multiple workers. Also what is different if we use multiple process compared to multiple workers. Can you provide a link which has the implementation of the message queue

**Comment by miguelgrinberg** [comment]
One gunicorn worker can handle hundreds/thousands of clients when using eventlet or gevent. If that is within your needs, then you should not worry about multiple processes.

If you do need to use multiple processes, then the documentation covers how to configure a message queue and a load balancer.

**Comment by ravimaharjan** [comment]
The documentation of flask-socketio says the Gunicorn release 19.x have incompatibilities in certain deployment scenarios that include WebSocket. I am using the Gunicorn version 19.6.0. So can I assume WebScoket would not work in my case.

**Comment by miguelgrinberg** [comment]
@ravimaharjan Actually, that note needs to be removed, that used to be a problem with the early 19.x releases, but the problems have been resolved now.

**Comment by njavilas2015** [comment]
it is correct with a worker it works great

the command gunicorn sarys.wsgi --workers = 1 -k "geventwebsocket.gunicorn.workers.GeventWebSocketWorker" --bind 0.0.0.0:80
