### ISSUE TITLE
TypeError when disconnecting

### ISSUE THREAD

**Issue by briehanlombaard** [miguelgrinberg/python-engineio#3]
Hi Miguel,

I'm using the new version of Flask-SocketIO and when I connect and subsequently disconnect, I get this error after a short time:

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 32, in __call__
        return self.engineio_app.handle_request(environ, start_response)
      File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 286, in handle_request
        return self.eio.handle_request(environ, start_response)
      File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 220, in handle_request
        environ, start_response)
      File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 77, in handle_get_request
        raise
    TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

Everything keeps running though so it's not a major issue. I've looked into it on my side and it looks like when you try to re-raise the IOError in handle_get_request Python has lost the reference to that exception.

This change seems to fix the problem:

    index 240ea43..268313d 100755
    --- a/engineio/socket.py
    +++ b/engineio/socket.py
    @@ -74,9 +74,9 @@ class Socket(object):
                                                               start_response)
             try:
                 packets = self.poll()
    -        except IOError:
    +        except IOError as e:
                 self.close(wait=False)
    -            raise
    +            raise e
             return packets
     
         def handle_post_request(self, environ):

It's a simple enough change, but let me know if you would prefer a pull request.

**Comment by miguelgrinberg** [comment]
Thanks, I'll incorporate this change. But can you tell me how can I reproduce this error? How do you disconnect to cause this?

**Comment by briehanlombaard** [comment]
I just go to a page where a socketio connection is created, then navigate away to another page.

After looking into this further it looks like it could be caused by my disconnect handler:

    @socketio.on('disconnect')
    def disconnect():
        print('client disconnected', request.sid)

When I remove that I don't get the error anymore. Am I doing something wrong?

**Comment by miguelgrinberg** [comment]
No, what you are doing should be supported. I don't think I have included `request.sid` in any disconnect handlers I tested, maybe that's what causes the problem. I'll look into it, thanks!

**Comment by miguelgrinberg** [comment]
This fix is included in release 0.6.4. Thanks!
