### ISSUE TITLE
module 'engineio' has no attribute 'WSGIApp' still after many tries reinstalling

### ISSUE THREAD

**Issue by namechangezero** [miguelgrinberg/python-engineio#302]
**IMPORTANT**: If you have a question, or you are not sure if you have found a bug in this package, then you are in the wrong place. Hit back in your web browser, and then open a GitHub Discussion instead. Likewise, if you are unable to provide the information requested below, open a discussion to troubleshoot your issue.

**Describe the bug**
I installed python-socketio with pip on my raspberrypi.
Now whenever i start my server, this probelm occurs:
```
Traceback (most recent call last):
  File "/home/pi/Coding/weather_and_room/server/server.py", line 6, in <module>
    import socketio
  File "/home/pi/.local/lib/python3.9/site-packages/socketio/__init__.py", line 12, in <module>
    from .middleware import WSGIApp, Middleware
  File "/home/pi/.local/lib/python3.9/site-packages/socketio/middleware.py", line 4, in <module>
    class WSGIApp(engineio.WSGIApp):
AttributeError: module 'engineio' has no attribute 'WSGIApp'
```

**To Reproduce**
1. Install python-socketio
2. start server.py

**Expected behavior**
I expect it not to show this error.
I already did much research about that error (including issues in this repo), tried everything but i still got this error

How can i solve this?
I have installed python-engineio-4.3.4

**Comment by miguelgrinberg** [comment]
My guess is that this is a problem in your own environment.

Open a Python shell, type the following:

```python
>>> import engineio
>>> print(engineio)
```

Show me the output. Also, you may want to include `server.py`, which you referenced in your report but have not provided source for.

**Comment by namechangezero** [comment]
> My guess is that this is a problem in your own environment.
> 
> Open a Python shell, type the following:
> 
> ```python
> >>> import engineio
> >>> print(engineio)
> ```
> 
> Show me the output. Also, you may want to include `server.py`, which you referenced in your report but have not provided source for.

Yes I already did this and not every Class which should be there was there.
But i did a reinstall of my whole operating system because it was somehow kinda strange and it's now fixed.
Thank you anyways!!
