### ISSUE TITLE
SIGINT should not close the event loop for the AsyncClient

### ISSUE THREAD

**Issue by mattpepin** [miguelgrinberg/python-engineio#306]
I spent a long time trying to figure out why my program was behaving badly on SIGINT. It turns out engineio closes the loop on SIGINT. I understand the use of the handler to disconnect, but why close the loop? Let asyncio do its thing. I'm not even sure the handler works correctly, as it creates a new task on a loop that will be closed.

**Comment by miguelgrinberg** [comment]
This change was made long ago, so I don't remember the particulars, but the reason it was added was that it caused Ctrl-C to block (https://github.com/miguelgrinberg/python-engineio/issues/197).

Do you have an example that you want to share that demonstrates your issue?

**Comment by mattpepin** [comment]
I removed the loop.close line and it works properly and removes all warnings. I can try to create a small repro.

**Comment by mattpepin** [comment]
Here's a small repro:

```
import asyncio
import socketio

async def main():
    sio = socketio.AsyncClient(handle_sigint=False)

    try:
        await sio.connect('http://localhost:6543', wait=True)
        print('Connected!')
        await sio.wait()
    finally:
        await sio.disconnect()

if __name__ == '__main__':
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print('Exiting...')
```

With handle_sigint=False:
```
Connected!
^Cpacket queue is empty, aborting
Exiting...
```

With handle_sigint=True:
```
Connected!
^Cpacket queue is empty, aborting
Traceback (most recent call last):
  File "/home/matt/repro.py", line 16, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 647, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe57dacc160>
Exception ignored in: <function ClientResponse.__del__ at 0x7fe57df5d750>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 811, in __del__
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 178, in release
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 663, in _release
  File "/usr/lib/python3.10/site-packages/aiohttp/client_proto.py", line 63, in close
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 706, in close
  File "/usr/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```

The RuntimeError is caused by the loop being closed.

On a side note, I think that the asyncio.CancelledError should not print the "packet queue is empty, aborting" message. It is expected on a clean shutdown.
~

**Comment by miguelgrinberg** [comment]
Thanks, I'll go back to that old issue and try to remember how the loop closing helped there.

> On a side note, I think that the asyncio.CancelledError should not print the "packet queue is empty, aborting" message. It is expected on a clean shutdown.

Yes, I agree, the cancelled error should log an error (the empty and timeout cases still should, though). Will make a correction here as well.

**Comment by miguelgrinberg** [comment]
Can I ask you to test something out on your side?

This is the exception handler I'm currently using, which appears to work for both your issue and #197:

```python
def async_signal_handler():
    """SIGINT handler.

    Disconnect all active async clients and cancel all tasks.
    """
    async def _handler():
        for c in client.connected_clients[:]:
            if c.is_asyncio_based():
                await c.disconnect()
        else:  # pragma: no cover
            pass

        # cancel all running tasks
        tasks = [task for task in asyncio.all_tasks() if task is not
             asyncio.current_task()]
        for task in tasks:
            task.cancel()
        await asyncio.gather(*tasks, return_exceptions=True)
        asyncio.get_event_loop().stop()

    asyncio.ensure_future(_handler())
```

This will cancel all running tasks, so you will be getting `asyncio.CancelledError` and not `KeyboardInterrupt`. Other than that I think it should allow you to exit cleanly.

I would have preferred not to meddle with the tasks (or even stopping the loop), but the signal handling in asyncio is fairly limited, with a single handler per signal allowed, so if this handler is installed, then it needs to do all the clean up work as there cannot be another one. At least that's what it appears from reading the code.
