### ISSUE TITLE
aiohttp session not closed if never connected

### ISSUE THREAD

**Issue by mattpepin** [miguelgrinberg/python-engineio#307]
Repro:

```
import asyncio
import socketio

async def main():
    sio = socketio.AsyncClient(handle_sigint=True)

    try:
        await sio.connect('http://localhost', wait=True)
        await sio.wait()
    finally:
        await sio.disconnect()
        # await sio.eio.http.close()

asyncio.run(main())
```

With the comment (unwanted unclosed client session):
```
socketio.exceptions.ConnectionError: Cannot connect to host localhost:80 ssl:default [Connect call failed ('127.0.0.1', 80)]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f1c6b9c8070>
```

Without the comment (expected):
`socketio.exceptions.ConnectionError: Cannot connect to host localhost:80 ssl:default [Connect call failed ('127.0.0.1', 80)]`

However, the http session is closed if the connection was successful at some point.

**Comment by miguelgrinberg** [comment]
Okay, I'll look into this one as well.

Note that when `sio.wait()` returns you are already disconnected, no need to call disconnect again, as it will do nothing.

**Comment by mattpepin** [comment]
Right! I re-used the other repro and changed it a bit. ;)
