### ISSUE TITLE
Any hope for python 3.11 support in python-engineio 3.x?

### ISSUE THREAD

**Issue by graham33** [miguelgrinberg/python-engineio#313]
I maintain some software which is unfortunately stuck on python-engineio 3.x and python-socketio 4.x, since the server uses an older version of the socketio protocol, and I don't control it. I use this as part of the Home Assistant ecosystem, which is starting to migrate to python 3.11 (https://www.home-assistant.io/blog/2023/03/01/release-20233/#python-311-support).

I'm hoping to get out in front of this upgrade and start using python 3.11 ASAP, but python-engineio 3.x current doesn't work on 3.11 due to use of some deprecated features. I believe these were already fixed in python-engineio 4.x - is there any hope of getting similar fixes for 3.x (and similarly for python-socketio 4.x)? I'm hoping I don't have to make my own forks.

Thanks for the hard work on these libraries over the years!

**Comment by miguelgrinberg** [comment]
No, the last 3.x release came out about 2.5 years ago. That branch become unsupported when the Socket.IO org updated their protocol in a backward incompatible way. Unfortunately I don't have the resources to maintain old releases that have practically no use today. Sorry.
