### ISSUE TITLE
Eventlet forces an 8MB max size on WebSocket packets

### ISSUE THREAD

**Issue by miguelgrinberg** [miguelgrinberg/python-engineio#319]
Discussed in https://github.com/miguelgrinberg/Flask-SocketIO/discussions/1998

Eventlet imposes its own maximum frame length, which conflicts with the maximum configured in this package. The solution is to reconfigure eventlet to use the same max length as this package.

**Comment by Pxmme** [comment]
Hi there,

Sorry for commenting on a closed issue. I see that you've implemented a fix, but I'm unsure about how to use it. :(

How can I increase the max size for packets being received by my socketIO server when using eventlet?

What's the option to pass to it?

Here is how I currently initialize things:

```python
socketio = SocketIO(app, cors_allowed_origins="*", logger=False, engineio_logger=False, ping_timeout=300000, ping_interval=300000)
if __name__ == '__main__':
    eventlet.wsgi.server(eventlet.listen(('0.0.0.0', 5000)), app, log_output=True)
```

Yeah, I've used insane ping timeouts and intervals lol, I'm currently battling with websockets disconnecting whenever my users send a packet that's too big D: (they are sending recorded audios to my server so size can vary)

Thanks in advance for any kind of help you may offer me, I'll truly appreciate it!

Cheers,
Pxmme

**Comment by miguelgrinberg** [comment]
@Pxmme Pass the `max_http_buffer_size` argument when you create your `SocketIO` object to configure the maximum allowed size. The default is 1MB.

**Comment by Pxmme** [comment]
@miguelgrinberg Yep, this fixed my issue. I added 100*1024*1024 to make sure to allow 100MB files tops.

Anyway, thanks a lot for your help! I appreciate it. Have a great sunday!
