### ISSUE TITLE
Client sending a PING packet to a closed socket raises IOError

### ISSUE THREAD

**Issue by igorzamyslov** [miguelgrinberg/python-engineio#32]
Good day to you!
I have a question concerning the problem in the title.
What I believe is happening and why does a server gets a PING packet from a disconnected user:
1. Client sends a lot of requests through socket.
2. Client's browser gets stuck on some request and client's socket misses sending a PING packet
3. Server closes a socket because of the timeout when trying to send a response to a request sent earlier (Socket.py, line 63, I get "Client is gone, closing socket")
4. Client sends it's PING packet at pretty much the same time
5. Server gets the PING packet and automatically tries to send a PONG, without checking that socket is closed (Socket.py, line 47)
6. In send function (Socket.py, line 58) there is a check that socket is closed -> raises IOError

My questions are:
- Should a Socket.py contain a check before sending a PONG or is it intended to be this way?
- If latter: is there any place I can add a check for PING packet that socket is closed myself? (without changing a library itself)

I hope the problem is clear.
If it will be necessary, I believe I can provide a log for that

**Comment by miguelgrinberg** [comment]
Is there a problem when this `IOError` is raised? That should be a benign error, meaning that all other clients should continue to be connected and working normally.

The situation that you describe is abnormal, I think it is warranted to raise an error when this type of problem occurs.

**Comment by igorzamyslov** [comment]
There's no real problem with application after an error, but I was just wondering, if there's a way to catch it somewhere except your library.

I guess you right, that this behavior is abnormal (as I understand, a client should receive disconnect command from server in time before sending somethin else), yet this problem is easily reproducible with small values of ping_interval and ping_timeout plus some load on socket (a number of requests) and client itself (browser, for my example).

Thank you for your time and response!
