### ISSUE TITLE
Bug with closing socket connection after ping-pong timeout

### ISSUE THREAD

**Issue by GrigorevGrigorii** [miguelgrinberg/python-engineio#323]
Server doesn't close the socket connection after ping-pong timeout
1. For checking timeout there is the regular task ([link](https://github.com/miguelgrinberg/python-engineio/blob/main/src/engineio/asyncio_server.py#L481-L481))
2. This task calls [check_ping_timeout](https://github.com/miguelgrinberg/python-engineio/blob/main/src/engineio/asyncio_socket.py#L54-L54) method to check if there is a ping-pong timeout
3. In the case of timeout this method calls [self.close](https://github.com/miguelgrinberg/python-engineio/blob/main/src/engineio/asyncio_socket.py#L113-L113) to close the connection in which if the condition `not self.closed and not self.closing` is `True` `self.closing` is set to `True` and then [self.send](https://github.com/miguelgrinberg/python-engineio/blob/8051fc49f484585b786031a08617208efdc97f5a/src/engineio/asyncio_socket.py#L69-L69) method is called with packet `CLOSE` for disconnection
4. However in `send` method there is an [extra call](https://github.com/miguelgrinberg/python-engineio/blob/8051fc49f484585b786031a08617208efdc97f5a/src/engineio/asyncio_socket.py#L71-L71) of `check_ping_timeout` that returns `False` as the timeout has occurred. In this extra call of `check_ping_timeout` there is an extra call of `close` that [ignores](https://github.com/miguelgrinberg/python-engineio/blob/8051fc49f484585b786031a08617208efdc97f5a/src/engineio/asyncio_socket.py#L115-L115) it as `self.closing is True`. And that is why the packet `CLOSE` was not sent

It describes the reason why server does't interrupt connection after ping-pong timeout but remove connection info. Because of that client still think that connection is open (and it is true) and continue sending packets but srver cannot process them
It can be easily fixed by changing [this condition](https://github.com/miguelgrinberg/python-engineio/blob/8051fc49f484585b786031a08617208efdc97f5a/src/engineio/asyncio_socket.py#L71-L71) to something like `not (self.closing and pkt.packet_type == packet.CLOSE) and not await self.check_ping_timeout()`

This photo of logs confirms this theory (look at [log](https://github.com/miguelgrinberg/python-engineio/blob/8051fc49f484585b786031a08617208efdc97f5a/src/engineio/asyncio_socket.py#L60-L60) `Client is gone, closing socket` with the same time)
![image](https://github.com/miguelgrinberg/python-engineio/assets/55593191/2c7a0535-a84f-414a-a9fd-ac1bb510d68b)

Version of packages:
```
python-socketio==5.5.0
python-engineio==4.3.1
```

**Comment by miguelgrinberg** [comment]
Why do you need the `CLOSE` packet to be sent? If a timeout has occurred the server assumes the client is gone and does not attempt to talk to it anymore.

**Comment by GrigorevGrigorii** [comment]
Because it is not always true. Sometimes the client takes too long to respond (but respond anyway later). And in such case the connection is still active, but server think that the client is not connected more. Because of this client still tries to send new messages, but server cannot process them
According to the [code](https://github.com/miguelgrinberg/python-engineio/blob/8051fc49f484585b786031a08617208efdc97f5a/src/engineio/asyncio_socket.py#L65) you try to close the connection but it doesn't work properly
At least it would be much better to have the possibility to configure this behaviour

**Comment by miguelgrinberg** [comment]
The assumption is that if the client does not respond to a ping it is gone. If your clients take longer to respond, then the correct thing to do would be to adjust the ping timeout and better yet would be to make the client responsive enough to respond to all pings promptly.

As explained in the code comments, sending a CLOSE packet in this situation is not done because it is expected the client will receive it, it is done with the assumption that the write will fail (usually with an `EPIPE` error), and this will update the state of the socket to disconnected. The fact that this is a CLOSE packet doesn't matter either, the point is to write something on the socket to trigger an update of its state.
