### ISSUE TITLE
Release v1.1.2 is not tagged

### ISSUE THREAD

**Issue by mckelvin** [miguelgrinberg/python-engineio#34]
Hi there, the version [v1.1.2](https://github.com/miguelgrinberg/python-engineio/commit/7b94fadf9a96509068a2c0f34b758149e8bd9159) has been release but it's [not tagged](https://github.com/miguelgrinberg/python-engineio/tags) yet.

**Comment by miguelgrinberg** [comment]
Sorry about that, the tag is up now.
