### ISSUE TITLE
at fastapi  0.109.0 version has some problem

### ISSUE THREAD

**Issue by human1001** [miguelgrinberg/python-engineio#341]
In fastapi version 0.109.0, the line 57 scope['path'] path in asgi.py is provided as /abc/socket.io if the route is defined as /abc. This will never achieve /socket.io compliance. Suggest to change line 57 startswith to "self.engineio_path in scope['path']" in asgi.py, so that it also conforms to the fastapi rules.

**Comment by miguelgrinberg** [comment]
If you want to use a non-standard Socket.IO path such as `/abc/socket.io`, pass the path you want to use to the `ASGIApp` class as follows:

```python
import socketio
app = socketio.ASGIApp(sio, socketio_path='/abc/socket.op')
```

**Comment by human1001** [comment]
> If you want to use a non-standard Socket.IO path such as `/abc/socket.io`, pass the path you want to use to the `ASGIApp` class as follows:
> 
> ```python
> import socketio
> app = socketio.ASGIApp(sio, socketio_path='/abc/socket.io')
> ```

It's normal. Thank you.
