### ISSUE TITLE
Rename async

### ISSUE THREAD

**Issue by AlexElvers** [miguelgrinberg/python-engineio#36]
In Python 3.7, `async` and `await` will be keywords (see [PEP 492#Deprecation Plans](https://www.python.org/dev/peps/pep-0492/#deprecation-plans)). Therefore, the `async` dicts in `async_*.py` have to be renamed.

**Comment by miguelgrinberg** [comment]
Good call. These are private dicts, so I can rename them without too much fuss. Thanks!
