### ISSUE TITLE
disconnect without sid causes RuntimeError

### ISSUE THREAD

**Issue by maybephilipp** [miguelgrinberg/python-engineio#368]
**Describe the bug**
Disconnect loop causes an exception since dict changes size during iteration

https://github.com/miguelgrinberg/python-engineio/blob/6650be6378d4aaa6e052590de48cdd8d714dbcb8/src/engineio/server.py#L183

**To Reproduce**
1. Call disconnect without sid argument

**Expected behavior**
Change the line to `for client in tuple(self.sockets.values())`

**Logs**
```
    for client in self.sockets.values():
RuntimeError: dictionary changed size during iteration
```

**Comment by miguelgrinberg** [comment]
@maybephilipp Would you be able to install the main branch and confirm the issue is resolved? Thanks!
