### ISSUE TITLE
Documentation of AsyncServer is not generated

### ISSUE THREAD

**Issue by AlexElvers** [miguelgrinberg/python-engineio#38]
On readthedocs, `AsyncServer` is empty. As far as I can see, readthedocs uses the wrong Python version so that `AsyncServer` is `None`.

**Comment by miguelgrinberg** [comment]
I'll investigate. I have it configured to build the docs using Python 3.x, but I'm not sure which version readthedocs uses. If they are using 3.4 or older then none of the async stuff will be loaded.

**Comment by miguelgrinberg** [comment]
Confirmed, readthedocs currently uses Python 3.4 to build docs when configured for Python3.

**Comment by miguelgrinberg** [comment]
This is now fixed. I was allowed into the readthedocs new builder, still in beta.
