### ISSUE TITLE
replace ACCEPT_ENCODING with  HTTP_ACCEPT_ENCODING

### ISSUE THREAD

**Issue by net21** [miguelgrinberg/python-engineio#39]
The gzip not working! 

should use HTTP_ACCEPT_ENCODING to replace ACCEPT_ENCODING at line 290 in server.py to fix this bug.
from:
environ.get('ACCEPT_ENCODING', '').split(',')]
to 
environ.get('HTTP_ACCEPT_ENCODING', '').split(',')]

**Comment by miguelgrinberg** [comment]
Good catch. Thanks!
