### ISSUE TITLE
AsyncServer.handle_request throws unhandled KeyError exceptions

### ISSUE THREAD

**Issue by ishmelev23** [miguelgrinberg/python-engineio#391]
I saw [this issue](https://github.com/miguelgrinberg/python-socketio/issues/302)  in SocketIO issues section before, but by some reason it wasn't considered a bug.

**Describe the bug**
When Socket is closed, but hasn't been deleted from memory of BaseServer, it causes KeyError('Session is disconnected`) exceptions which are unhandled by EngineIO or SocketIO servers.
The exception is raised from this method: https://github.com/miguelgrinberg/python-engineio/blob/a6e5d92ca98b41d2054737c6c49fc0511da0c3c6/src/engineio/base_server.py#L227-L229
when client continue to send polling GET requests and it ends up here (probably POST as well, but we didn't notice errors related to POST) https://github.com/miguelgrinberg/python-engineio/blob/a6e5d92ca98b41d2054737c6c49fc0511da0c3c6/src/engineio/async_server.py#L286-L291

In some cases it's expected behavior and handled properly, like https://github.com/miguelgrinberg/python-engineio/blob/a6e5d92ca98b41d2054737c6c49fc0511da0c3c6/src/engineio/async_server.py#L114-L120
and
https://github.com/miguelgrinberg/python-engineio/blob/a6e5d92ca98b41d2054737c6c49fc0511da0c3c6/src/engineio/async_server.py#L189-L197

Apparently, it's some kind of race condition when the socket has been closed, but wasn't deleted by service task
https://github.com/miguelgrinberg/python-engineio/blob/a6e5d92ca98b41d2054737c6c49fc0511da0c3c6/src/engineio/async_server.py#L548-L556

The issue is that: the server shouldn't raise an unhandled exception when the client sends requests which are not consistent with the server's internal state.
Right now we handle it by ourselves, but I believe that exceptions related to server's internal state should be managed by server itself.

**To Reproduce**
Hard to say how to reproduce it in e2e manner, because it just happens in production, and it's flaky, I didn't find a reason, why the closed Socket stays in sockets dictionary of AsyncServer.

But it could be reproduced in unit tests:
1. Start connection.
2. Close connection from client side (so the socket will be closed on the server side).
3. Immediately send polling request to the server.

**Expected behavior**
In that case, I expect that request will end up in branch and I get BadRequest error from server:
https://github.com/miguelgrinberg/python-engineio/blob/a6e5d92ca98b41d2054737c6c49fc0511da0c3c6/src/engineio/async_server.py#L287-L288
Bot not in 
https://github.com/miguelgrinberg/python-engineio/blob/a6e5d92ca98b41d2054737c6c49fc0511da0c3c6/src/engineio/async_server.py#L289-L309

**Logs**
In logs, I see common pattern: socket either was closed by server, either client itself dropped connection, then this unhandled error happens, when client continue to send GET/POST requests (checked about 15 cases manually).
If my assumption isn't correct, and you need detailed logs, please tell me I will collect it for you.

**Idea of bugfix**
Seems like it would be just enough to rewrite this part for handling GET/POST:
https://github.com/miguelgrinberg/python-engineio/blob/a6e5d92ca98b41d2054737c6c49fc0511da0c3c6/src/engineio/async_server.py#L286-L290

Handling KeyError as missing socket, then if socket is empty, we will go to the logical branch with bad request, otherwise continue processing request.

**Additional context**
In our team, we use SocketIO along with FastAPI.
We accept requests from clients with different platforms IOS, Android, Web.
Caught it even on low traffic ~1 rps.
Version: 4.9.1 of EngineIO, but as I see, the same code is till present in main branch.

**Comment by miguelgrinberg** [comment]
I have not removed these exceptions because when these conditions occur it is a clear indication that you have a problem that you need to address. You are implying that this is an internal server issue, but it isn't. This error means that your clients are missing the deadlines to respond to PING packets, or that your server is so busy that it is unable to process the PONG responses from the clients in a timely manner (as I explained many many times in the issues this is discussed). Either way if you see these often then you have a problem that needs to be looked into, and reducing the visibility of these errors may make you less aware of the problem.

But I guess I could be convinced to downgrade this to an error log that does not include the stack trace.

**Comment by ishmelev23** [comment]
> But I guess I could be convinced to downgrade this to an error log that does not include the stack trace.

Yes, in general, that's what I'm talking about.

> I have not removed these exceptions because when these conditions occur it is a clear indication that you have a problem that you need to address. 

In the expected behavior I mentioned, that this issue could be handled by this branch of code
https://github.com/miguelgrinberg/python-engineio/blob/a6e5d92ca98b41d2054737c6c49fc0511da0c3c6/src/engineio/async_server.py#L287-L288
Here we log the exception and respond with bad request to the client.
This way we keep the issue visible for the client and keep it visible for the developer.

Is there a specific reason that we need to crash the server by unhandled exception without responding to the client with structured response?

**Comment by ishmelev23** [comment]
Also, the reason, why I'm assuming that this is a bug, because if some time passes, the `sid` will be deleted from `sockets` dictionary (because will be garbage collected by `service task`).
What makes all these requests end up in the branch:
https://github.com/miguelgrinberg/python-engineio/blob/a6e5d92ca98b41d2054737c6c49fc0511da0c3c6/src/engineio/async_server.py#L287-L288

So the situation is still the same: e.g. client disconnects from server.
But reaction is different based on the fact: did `service task` managed to delete closed socket from `sockets` dict or didn't.
In the first case, we will properly respond with bad request and log this issue with logger.
In the second case, an unhandled exception will be raised by method `handle_request`

So it looks like, it is just a race condition, isn't?

**Comment by miguelgrinberg** [comment]
You are assuming that the "Invalid session" error has the same purpose, but it is there to cover mainly other problems, such as the server receiving an invalid sid that never existed, or a sid that is owned by a different worker. In these cases the server does not have enough information to provider a better error message.

But when the server receives a sid that was recently closed it can give you a slightly more informative message. You are correct that eventually the server will forget about this sid and if the client continues to send requests they'll be logged with the invalid message, but clients are unlikely to insist anyway, so logging the first (and possibly only) error as a disconnected session makes sense to me.

**Comment by ishmelev23** [comment]
Got your idea, thanks.

> logging the first (and possibly only) error as a disconnected session makes sense to me, even if it isn't always possible due to timing.

This sounds great. If you need any assistance with pull request, please let me know.

Generally, I think it will be enough, because most probably most developer set up their monitoring systems and track error rate. 
So the spike or high amount of bad request responses will totally attract attention of dev team, then they could check logs and error monitoring system for deeper investigation of this issue. 
Crashing the app or responding with 500 error is unnecessary IMHO.
