### ISSUE TITLE
"ValueError: filedescriptor out of range in select()" appear when open a lot of long connection

### ISSUE THREAD

**Issue by JianMingZhuo** [miguelgrinberg/python-engineio#40]
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/engineio/async_gevent_uwsgi.py", line 52, in select_greenlet_runner
    select([fd], [], [])[0]
  File "/usr/local/lib/python2.7/dist-packages/gevent/select.py", line 141, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
ValueError: filedescriptor out of range in select()
Mon Feb 27 17:07:49 2017 <Greenlet at 0x7faeadac3e10: select_greenlet_runner(5228, <gevent.event.Event object at 0x7faeada83d50>)> failed with ValueError
```

I get this exception when get a lot of long connection.

I use flask + flask-SocketIO + gevent + uwsgi as the server.

I found than flask-SocketIO base on the python-engineio, and python-engineio use ```select()```.

```select()``` limit 1024 fd.

**Comment by miguelgrinberg** [comment]
Could you try the master branch of this repository? Let me know if that addresses the problem.

**Comment by JianMingZhuo** [comment]
Thanks! It seem fixed. But is it a better way to use ```epoll()```? ```epoll()``` may be faster and not limit 1024 fd.

**Comment by miguelgrinberg** [comment]
I believe gevent does not support epoll yet.

**Comment by JianMingZhuo** [comment]
Yes, I found it too, But gevent support ```poll```, this has no 1024 fd limit.
