### ISSUE TITLE
line length

### ISSUE THREAD

**Issue by phls** [miguelgrinberg/python-engineio#45]
Hi Miguel,

I'm packaging python-engineio to Debian to be used in other python project.
But I have an issue with these files:
examples/aiohttp/static/engine.io.js line length is 801 characters (>512)
examples/sanic/static/engine.io.js line length is 801 characters (>512)
examples/wsgi/static/engine.io.js line length is 801 characters (>512)

Is it possible you break these lines and make a new release?

Thanks.

**Comment by miguelgrinberg** [comment]
That's a vendored file, not part of this project. I would rather have you not package the examples, which really have no reason to be included in the installation.

**Comment by phls** [comment]
Ok, thanks.

**Comment by phls** [comment]
Hi @miguelgrinberg 

The best solution is if you release a new version without the examples folder.
Could you do that?

Thanks.

**Comment by miguelgrinberg** [comment]
My releases do not include the examples. Where did you see an official release that includes examples?

**Comment by phls** [comment]
I downloaded from here, v1.3.1
https://github.com/miguelgrinberg/python-engineio/releases/tag/v1.3.1

**Comment by miguelgrinberg** [comment]
That's not a release, that's github zipping up the whole repo. I have no way to control what goes in those zip files, github puts all the files there.

The officlal releases are in the Python package repository: https://pypi.python.org/pypi/python-engineio/1.3.1
