### ISSUE TITLE
Ping Timeout Too Tight

### ISSUE THREAD

**Issue by chrisknight32** [miguelgrinberg/python-engineio#47]
Hello,

We recently noticed some instability with our websockets and I believe I've traced it down to the recent changes you've made regarding detecting lost connections. Essentially what happens is our connection will be dropped by the server due to a timeout exception because it didn't receive a ping recently enough.

However, you are setting the timeout to _exactly_ the interval at which the client will send pings. This means that even the slightest amount of network latency or load on the client will cause the server to drop the connection. May I recommend setting the server side timeout to be some multiple of the client side ping interval (like say 1.5) or make it configurable separately from the ping_interval?

For example, the defaults on the client side for the interval vs the timeout are 25 seconds and 60 seconds, respectively. So maybe the default multiplier you could use could actually be 2x the interval.

Let me know what you think.

Thanks,

-Chris

**Comment by maxim-s-barabash** [comment]
We get exactly the same behavior as described above.
With more than one subscription there is a regular disconnect.
python-engineio==2.0.2
async = async_gevent_uwsgi.py

**Comment by miguelgrinberg** [comment]
This issue has been fixed, so I'm closing. Please reopen if you still experience timeouts.
