### ISSUE TITLE
Fails on WebSocket disconnect in aiohttp

### ISSUE THREAD

**Issue by voronin-opensoft** [miguelgrinberg/python-engineio#48]
Hello. Python-engineio fails on Websocket disconnect in https://github.com/miguelgrinberg/python-engineio/blob/v1.5.2/engineio/async_aiohttp.py#L111
cause incorrect data type (integer 1001).
It affects **1.5** version only

**Comment by miguelgrinberg** [comment]
@voronin-opensoft can you add a complete stack trace of the error please? Thanks.

**Comment by miguelgrinberg** [comment]
I was able to reproduce this, here is the stack trace:

```
Task exception was never retrieved
future: <Task finished coro=<WebSocket.wait() done, defined at /home/miguel/Documents/dev/flask/python-engineio/engineio/async_aiohttp.py:107> exception=OSError()>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/miguel/Documents/dev/flask/python-engineio/engineio/async_aiohttp.py", line 112, in wait
    raise IOError()
OSError
```

**Comment by miguelgrinberg** [comment]
This turned out to be a bug in asyncio. Here is the [bug report](http://bugs.python.org/issue30508?@ok_message=file%2046911%20created%0Amsg%20294732%20created%0Aissue%2030508%20created&@template=item) I filed.

I will add a workaround in the mean time.
