### ISSUE TITLE
incorrect traceback on application error 

### ISSUE THREAD

**Issue by intra-au** [miguelgrinberg/python-engineio#49]
socket.py keeps exception in reraise_exc variable and try to raise it with "raise reraise_exc", however that's causing wrong traceback on stderr.
Since the blank raise raises the last exception below is the fix (I've commented raise "reraise_exc" and just use "raise"
        if reraise_exc:
            raise

the problem it was causing is the last line of traceback was:

> ---
> File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 230, in _websocket_handler      
>   raise reraise_exc                                                                                    
> --

using just raise it displays correct traceback for the previous exception

**Comment by miguelgrinberg** [comment]
@intra-au can I ask you to install the master branch direct from git and confirm that the problem is resolved? Thanks!
