### ISSUE TITLE
Use UltraJSON or others for packet serialization (feature request)

### ISSUE THREAD

**Issue by peter-conalgo** [miguelgrinberg/python-engineio#5]
I'd like to be able to use [UltraJSON aka ujson](https://pypi.python.org/pypi/ujson) because the assumption is it would be faster than whatever "import json" gives.

In other projects, I'd like to use SimpleJSON because it handles decimals correctly.

Sometimes I need to pass arguments into the decoder too.

So, please consider adding an interface so the JSON decoder/encoder object can be specified and be project-specific.

Thanks!

**Comment by miguelgrinberg** [comment]
Makes sense, I'll look into it.

**Comment by miguelgrinberg** [comment]
This is now implemented, both here and in python-socketio.
