### ISSUE TITLE
Strange invalid session behavior

### ISSUE THREAD

**Issue by cjnolet** [miguelgrinberg/python-engineio#50]
I'm trying to get an IOS app to use the flask-socketIO library and I'm having quite a bit of trouble establishing sessions it seems. I've got my sessions set up according to the flask-sessions website (I was using beaker but that was causing problems so I switched to regular flask-sessions). Here's my session setup code:

```
session_opts = {
    'SESSION_TYPE': 'redis',
    'SESSION_PERMANENT': True,
    'SESSION_COOKIE_NAME':'session_cookie'
}

```

I'm also doing this to make the sessions permanent though It's strange I'm not seeing them show up in redis:

```
@app.before_request
def make_session_permanent():
    session.permanent = True
    app.permanent_session_lifetime = timedelta(minutes=380)
```

The problem I'm having is that I consistently see the socketio sessios being invalidated. This is what' shappening:

```
18a6bf976a2244afa34e9283f47c3b24: Sending packet OPEN data {'pingInterval': 50000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': '18a6bf976a2244afa34e9283f47c3b24'}
18a6bf976a2244afa34e9283f47c3b24: Sending packet MESSAGE data 2["my response",{"data":"Connected"}]
18a6bf976a2244afa34e9283f47c3b24: Sending packet MESSAGE data 0
18a6bf976a2244afa34e9283f47c3b24: Received packet PING data None
18a6bf976a2244afa34e9283f47c3b24: Sending packet PONG data None
18a6bf976a2244afa34e9283f47c3b24: Received packet MESSAGE data 2["user.connect",{"uname":"testuname2"}]
18a6bf976a2244afa34e9283f47c3b24: Sending packet MESSAGE data 2["my response",{"data":"Disconnected"}]
18a6bf976a2244afa34e9283f47c3b24: Sending packet CLOSE data None
Invalid session 18a6bf976a2244afa34e9283f47c3b24
f1185d7ccd5941b0b019f0f4f2102a3d: Sending packet OPEN data {'pingInterval': 50000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': 'f1185d7ccd5941b0b019f0f4f2102a3d'}
f1185d7ccd5941b0b019f0f4f2102a3d: Sending packet MESSAGE data 0
f1185d7ccd5941b0b019f0f4f2102a3d: Sending packet MESSAGE data 2["my response",{"data":"Connected"}]
caf94183328e44a4823b5cfdf0f90956: Sending packet OPEN data {'pingInterval': 50000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': 'caf94183328e44a4823b5cfdf0f90956'}
caf94183328e44a4823b5cfdf0f90956: Sending packet MESSAGE data 2["my response",{"data":"Connected"}]
caf94183328e44a4823b5cfdf0f90956: Sending packet MESSAGE data 0
```

Many times, I see "Invalidate session XXXXXXXXX" Just scrolls endlessly through the terminal. Any ideas on what the problem here could be?

**Comment by cjnolet** [comment]
Perhaps I'm using this tool incorrectly? I have this inside of my viewDidLoad() function in my ios app:

```        socket?.on("my response") {data, ack in
            self.socket?.emit("dj.connect", ["uname":self.uname])
        }
        
        socket?.on("user.connected") { data, ack in
            print("WONDERFUL!")
        }
```

**Comment by miguelgrinberg** [comment]
The "session" referenced in the logs and in error messages is the Socket.IO session, and that has nothing to do with the Flask sessions that your application uses. I know beaker sessions are incompatible, this was actually reported yesterday by another user, but my understanding is that Flask-Sessions works well.

Is there any reason you mention your session configuration other than thinking that the session in the error message referred to that?

In the log snippet that you included, the server is sending the "Disconnected" message back to the client. Are you doing that intentionally? It would be interesting to know who is calling the method that emits that event.

**Comment by cjnolet** [comment]
Miguel,

I love the fast responses! I was actually the user that posted about the
beaker sessions yesterday. I *believe* the problem was that I was not
including an argument in my functions on the server to hold the the data
that was being emitted from the client. So is this true that I couldn't
have this:

```
@socketio.on('user_connect')
def socket_connect_user():
    emit('user_connected')
```

and that I would need to change it to this:

```
@socketio.on('user_connect')
def socket_connect_user(data):
    emit('user_connected')
```


Youa re correct, by the way, I thought that perhaps the SocketIO session ID
was being stored in the Flask session and perhaps that was disappearing and
that's why it kept being "invalid".

**Comment by miguelgrinberg** [comment]
> I was actually the user that posted about the beaker sessions yesterday

Of course! I should have checked :)

The arguments in your server side event handlers depend on what you are sending from the client. If you send no arguments, then your handler should have no arguments. Typically events are sent with a single argument, so most commonly you will see event handlers taking an argument.

**Comment by cjnolet** [comment]
I think I see what's happening. The Swift client automatically sends no
arguments if I provide an empty list. I was confused- I figured it would
send an empty list of arguments but it looks like it actually nils it out
causing the server side to need to be configured with no arguments in the
functions.

Thanks again for your help! I think I've got it work as expected.
