### ISSUE TITLE
Not python2.7 compatible

### ISSUE THREAD

**Issue by stbuehler** [miguelgrinberg/python-engineio#53]
Although README.rst claims "Python 2.7" compatibility `async def` and `await` require Python 3.5 afaict.

**Comment by miguelgrinberg** [comment]
This package supports a number of async frameworks:

- eventlet
- gevent
- uwsgi+gevent
- asyncio+aiohttp
- asyncio+sanic

Only the last two are asyncio based, the top three are 2.7 compatible.

**Comment by stbuehler** [comment]
Ok. Sorry :)

I'd like to avoid installing incompatible source files (because debian tools really don't like it, and refuse to install packages with incompatible source). Any idea how to do that?

**Comment by miguelgrinberg** [comment]
Can you build your own package? Get the official package, delete what you don't want, and repackage?

**Comment by stbuehler** [comment]
The "official" package only is build for python3 (3.5) too: see https://packages.debian.org/source/sid/python-engineio.

For python2 I'd need to manually delete files after they were installed. Obviously it would be easier if the not-working files wouldn't be installed in the first place :)

I don't really need the python2 packages (I was working on https://build.opensuse.org/project/monitor/home:stbuehler:gdbgui which should run fine with python3), just would have preferred to do it "right".

**Comment by miguelgrinberg** [comment]
The package you referenced is not "official", I have nothing to do with that. The only "official" package is the one I build myself, which you can find here: https://pypi.python.org/pypi/python-engineio. There is a single package that works for all versions of Python. The modules that are Python 3.5 specific are never imported when you use the package under Python 2.

**Comment by bahendri** [comment]
Ran into this myself. To make debian packaging happy I used the following:

```
#!/usr/bin/make -f                                                                                                      
#export DH_VERBOSE = 1                                                                                                  
                                                                                                                        
export PYBUILD_NAME=engineio                                                                                            
                                                                                                                        
# PYBUILD_AFTER_BUILD is no good because setup.py invokes build_py which then restores the deleted files                
# override_dh_python2 -X asyncio_server.py... is no good because dh_python treats all .py files as "compile=True" and   
#                      fails to pass on the command-line args to the pycompile postinst script.                         
export PYBUILD_AFTER_INSTALL_python2=rm {destdir}/{install_dir}/engineio/asyncio_server.py {destdir}/{install_dir}/engineio/async_aiohttp.py {destdir}/{install_dir}/engineio/async_sanic.py {destdir}/{install_dir}/engineio/asyncio_socket.py
                                                                                                                        
%:                                                                                                                      
    dh $@ --with python2,python3 --buildsystem=pybuild                                                                  
                                                                                                                        
override_dh_auto_test:            
```
