### ISSUE TITLE
Bug in payload.py

### ISSUE THREAD

**Issue by aweffr** [miguelgrinberg/python-engineio#55]
I'm working on a small chat room project in python 3.6.

I find that the packet length has not adjusted correctly when I receive the packets in Chinese words.

Example:
**b'53:42/room1,["to_server",{"data":"\\u4f60\\u597d","topic":"public"}]'**
In Chinese, I just send a message: "你好".

In my runtime the program never goes to
```
packet_len += len(encoded_payload) - len(fixed_payload)
```
so I just add one more line under "encoded_payload = fixed_payload":
```
packet_len = len(fixed_payload)
```

Then my program starts to work well. I have not so much experience on dealing with bytes encoding, hoping for your response.

aweffr@qq.com

<img width="283" alt="qq" src="https://user-images.githubusercontent.com/17469534/27521485-13aa5f54-5a50-11e7-9667-2470abd59918.png">

**Comment by miguelgrinberg** [comment]
What version of the Socket.IO client are you using? There was a bug with encoding of unicode in all the 1.x Socket.IO clients. The bug was fixed in Socket.IO client 2.0, in a backwards incompatible way. I tried to make my server support both the 1.x and the 2.x clients, but maybe I made a mistake. Which version of the client are you using?

**Comment by aweffr** [comment]
Hi, glad to hear from you so quickly:)

According to pip list, I'm using python-socketio 1.7.5, Flask-SocketIO 2.8.6.

And I use gevent server.

Last week I also meet a bug that I can't emit a server generated message when I use eventlet, then I turn to gevent and the bug disappeared.

**Comment by miguelgrinberg** [comment]
I was not asking about your server versions. I need the version of your JavaScript Socket.IO client.

**Comment by aweffr** [comment]
The client version is 2.1.2

**Comment by aweffr** [comment]
Wait a minute...
I cached a js file as the static resource...
It's prodution version and I can't figure out the version number.

**Comment by miguelgrinberg** [comment]
Yeah, there is actually no 2.1.2 version. The current version is 2.0.3.

**Comment by aweffr** [comment]
OK, now I diff my file with 2.0.2 version.
I confirm that my version is 2.0.2

**Comment by miguelgrinberg** [comment]
What version of python-engineio do you have installed?
