### ISSUE TITLE
Socket.IO disconnection packets are parsed incorrectly

### ISSUE THREAD

**Issue by ntamas** [miguelgrinberg/python-engineio#6]
I'm not sure whether this issue belongs to here or to `python-socketio`, but I think it's more appropriate here.

I'm using Socket.IO 1.3.7 on the client side to connect to a Socket.IO server based on Flask-SocketIO 1.0b3 and eventlet. When I call the `disconnect()` method of the client-side socket, an Engine.IO packet with the contents `"41"` gets sent; this is basically an ordinary Engine.IO message (type=4) that wraps a Socket.IO close packet (type=1). However, the message body (i.e. the single-character string `"1"`) gets parsed as JSON in `Packet.decode()`, so when the packet reaches the Socket.IO layer, the body is not a string (`"1"`) any more but an integer (`1`). This causes an exception down in `python-socketio` at the following line in `packet.py`:

```
self.packet_type = int(ep[0:1])
```

since `ep` is an integer already and thus it cannot be sliced. I worked around it by parsing the Engine.IO message body as JSON only if it starts with `{` or `[`, but maybe there's a better solution.

Version numbers:

```
eventlet==0.17.4
Flask==0.10.1
Flask-SocketIO==1.0b3
python-engineio==0.7.1
python-socketio==0.6.0
```

**Comment by miguelgrinberg** [comment]
How is the example app I'm using in the Flask-SocketIO extension different from what you are doing? I can trigger a disconnect from the client with that application and everything seems to work, no crashes occur on the server, at least.

**Comment by ntamas** [comment]
The key difference seems to me that the example app only sends a disconnection request to the server and it is the server that initiates the disconnection. In my case, I simply call `socket.disconnect()` on the client side (from JavaScript).

**Comment by miguelgrinberg** [comment]
Oh, of course, right. Let me modify that example to do the disconnect from the client side, hopefully that'll reproduce it for me.

**Comment by miguelgrinberg** [comment]
Fixed in python-socketio
