### ISSUE TITLE
uwsgi worker cpu high with gevent and uwsgi

### ISSUE THREAD

**Issue by xinghua** [miguelgrinberg/python-engineio#61]
hi: 
     I use flask socketio with gevent_uwsgi mode，and use nginx as proxy .

uwsgi  key option:
http = :5000
http-websockets = 1
processes = 1
gevent = 10000
lazy-apps = true

many uwsgi instance run at the same time, and every instance use one http port like 5000, 5001 and so on

meanwhile in front of uwsgi instance,  I use many nginx proxy,  every nginx forward socktio request by nginx upstream ip_hash.  although socketio requests with same sid  may be hashed to different nginx, but every nginx use the same configuration to hash the request to the same uwsgi worker.  In my scene, client use various browser,  so socketio use websocket or long polling

sometimes I find the uwsgi worker cpu is so high,  nearly 100%. and I strace the uwsgi worker, find it busy with select system call 
select(42, [41], [], [], {0, 0})        = 1 (in [41], left {0, 0})
select(32, [31], [], [], {0, 0})        = 1 (in [31], left {0, 0})
select(25, [24], [], [], {0, 0})        = 1 (in [24], left {0, 0})
select(42, [41], [], [], {0, 0})        = 1 (in [41], left {0, 0})
select(32, [31], [], [], {0, 0})        = 1 (in [31], left {0, 0})
select(25, [24], [], [], {0, 0})        = 1 (in [24], left {0, 0})
select(42, [41], [], [], {0, 0})        = 1 (in [41], left {0, 0})

uwsgi worker log show many 500 or 400 requests,  but It seems that no so many clients use socketio connection at the same time.  exceptionally,  even I reload uwsgi worker,  restart uwsgi master, the cpu still very high immediately after reload.  and strace show uwsgi worker still busy with select call.

I've considered several reasons:
1  all strange request with transport polling, GET/POST/GET/POST,  BUT continuous two GET will cause some strange phenomenon? If different nginx proxy the requests with same sid, but the uwsgi worker receive these requests with different order as client sending them,  or with same sid and same timestamp requests be handled by socketio server, will cause exception?

2 why uwsgi busy with select? It seems that bug with race condition

Any help was appreciated and thank you very much

**Comment by miguelgrinberg** [comment]
Any chance you are doing something that blocks? You are using gevent, so each uwsgi process is going to run with a single thread. All the work that you do in your application must be greenlet friendly.

**Comment by xinghua** [comment]
so something blocks cause uwsgi worker busy with select system call?

**Comment by miguelgrinberg** [comment]
I haven't seen you analysis, but my guess is that the select call is not related to this problem. My question is that if your code has any operations that are blocking. This could be difficult to determine, it's not really a simple question. Anything I/O or thread/process related actions that you do in your application that are not directly supported by gevent will be blocking and that is bad.

**Comment by maxim-s-barabash** [comment]
try adding uwsgi key option:
**master = true**

**Comment by wangyang02** [comment]
@xinghua have you solved it?I came across the same problem:busy with select system call
