### ISSUE TITLE
engineio.exceptions.QueueEmpty

### ISSUE THREAD

**Issue by larry-dev** [miguelgrinberg/python-engineio#65]
@miguelgrinberg 
![wx20180313-131705](https://user-images.githubusercontent.com/18585750/37323908-6d167fa8-26c1-11e8-9f12-d34e6f55a5ac.png)

I don't understand why there's such a mistake.
Can you help me to confirm it.
Thank you very much.

**Comment by miguelgrinberg** [comment]
This is actually a bug, I need to fix it.
