### ISSUE TITLE
Deserializing data in packet as a JSON should be optional.

### ISSUE THREAD

**Issue by Hardtack** [miguelgrinberg/python-engineio#66]
In [packet.py](https://github.com/miguelgrinberg/python-engineio/blob/268e3cba424391dd32950d0ba08d28a65c4ef14b/engineio/packet.py#L83-L87), parser always try to deserialize data as JSON, even though engine.io protocol does not specify about JSON data.

I'm actually using python-engineio's packet class, and python-socketio's one to make socket.io client for python.
When I try to parse a message like `40` which means _connected_ packet `[type=CONNECT(0)]` in socket.io level, python-socketio's parser fails because of following steps.

1. python-engineio's parser parses `40` as a packet `[type=MESSAGE(4), data=0(integer)]` cause it parsed `0` as JSON string `0`
2. It put the data of engineio packet which is `0` to python-socketio's packet like `socketio.packet.Packet(encoded_packet=data)`
3. The non-zero test fails at [here](https://github.com/miguelgrinberg/python-socketio/blob/7f02f7aaa92c18c043466cb4721356221361f481/socketio/packet.py#L42) and then it parsed as a packet `[type=EVENT(2), data=None]`

It seems that it doesn't matter in server-side implementation. But, as I think, the parser should work for all valid cases.

**Comment by miguelgrinberg** [comment]
Okay, I understand the problem. My idea was to allow you to work with dictionaries and lists in a Pythonic way, but I think I went too far.

Would it work if I make it an option to do this deserialization?

**Comment by Hardtack** [comment]
How about just adding new attribute `raw_data`? since it does similar thing about base64 encoding.
I already saw socketIO-client but it was not suit for me since it is using gevnet. I’m making asyncio one :)

**Comment by miguelgrinberg** [comment]
The base64 decoding is done when the packet uses base64 internally, not when the user passes a raw payload that is encoded in base64. This is, I think, the right approach for this project. If the protocol internally encodes in base64 you as a client of this package do not need to deal with that.

**Comment by Hardtack** [comment]
You are right. It seems that making option would be right solution.

**Comment by miguelgrinberg** [comment]
I'm closing this, given that I have now implemented a Socket.IO client myself and addressed the problem in the parser as part of that effort.
