### ISSUE TITLE
async_redis & engine event-loop

### ISSUE THREAD

**Issue by juntiedt2** [miguelgrinberg/python-engineio#67]
Based on your aiohttp example I developed my IOT webserver which receives input through a redis queue and sends back IOT commands from my web site through another redis queue. Works great and fast.

In order to use async-redis I created another event-loop but I am not sure if this is the best way to do it. Shouldn't I use engine's event loop with async_redis? How can I access this loop? (app.loop?)

**Comment by juntiedt2** [comment]
server prog at https://github.com/juntiedt2/JU_1/blob/master/server5.py

**Comment by miguelgrinberg** [comment]
This package does not use its own loop, it basically attaches to a web application and uses the its loop. If you are using aiohttp, then yes, you should create your aioredis connection on the same loop. There is an example of how to do this here: https://docs.aiohttp.org/en/stable/web_advanced.html#background-tasks.
