### ISSUE TITLE
ping latency causing close connection

### ISSUE THREAD

**Issue by nuevoleonkx** [miguelgrinberg/python-engineio#68]
Hi,

I'm having this error: "Client is gone, closing socket" #19  but I have only one `sid`, to `'/'` and `'/custonnamespace'`

I see at logs on client and server side and apparently the reason is that ping event is not received by the server. 

```
def send(self, pkt):
        """Send a packet to the client."""
        if self.closed:
            raise exceptions.SocketIsClosedError()
        if time.time() - self.last_ping > self.server.ping_timeout:
            self.server.logger.info('%s: Client is gone, closing socket',
                                    self.sid)
            self.close(wait=False, abort=True)
            return
        self.queue.put(pkt)
        self.server.logger.info('%s: Sending packet %s data %s',
                                self.sid, packet.packet_names[pkt.packet_type],
                                pkt.data if not isinstance(pkt.data, bytes)
                                else '<binary>')
```

Client sends the `ping` event, then the server must receive that event, and almost inmediatly should respond with `pong` event. 

During the connection, some events are emmited and responding correctly, but because they perform some queries at database and takes some time, I see that after some minutes there is a latency between ping emmited by client, and this ping being received from server. 

Then according to the code above, if server tries to respond but the time elapsed from last ping is greater than `ping_timeout`, then causing close the connection.

So my questions are... Is a normal behaviour to have a latency? how can I deal with that? Should work if I change `ping_interval` and `ping_timeout` to avoid this error?

Thank you

**Comment by nuevoleonkx** [comment]
According to documentation:

```
:param ping_timeout: The time in seconds that the client waits for the
                         server to respond before disconnecting. The default
                         is 60 seconds
```

Maybe because some tasks require a lot of time, If I set `ping_timeout` to a greater value things goes better.

**Comment by miguelgrinberg** [comment]
It shouldn't matter if your tasks run for a long time, they should not block other tasks from running. I think you need to fix your application to not block.

**Comment by nuevoleonkx** [comment]
gevent.spawn()
