### ISSUE TITLE
sanic.exceptions.InvalidUsage: Method OPTIONS not allowed for URL /socket.io/

### ISSUE THREAD

**Issue by 3mp3ri0r** [miguelgrinberg/python-engineio#70]
Hi all. I got issue when try to connect javascript socketio-client to python-socketio with different server port due to socketio-client request with OPTIONS method like this:

> Request URL: http://localhost:8000/socket.io/?EIO=3&transport=polling&t=MDDnLi0
Request Method: OPTIONS
Status Code: 405 Method Not Allowed
Remote Address: [::1]:8000
Referrer Policy: no-referrer-when-downgrade

I've read the engine.io and I got that it doesn't add OPTIONS method in route, only GET and POST. I don't know is it a bug or I'm the one who implement it in a wrong way. Please guide me to solve this issue. Thanks.

N.B. My app locaton is http://localhost:8081.

**Comment by miguelgrinberg** [comment]
Yes, sanic needs an explicit declaration of the methods that are supported. Fix coming up soon.

**Comment by 3mp3ri0r** [comment]
Thank you so much @miguelgrinberg. I'll wait your update.

**Comment by miguelgrinberg** [comment]
@3mp3ri0r the master branch of python-engineio now has the fix for sanic. Would you like to test it to confirm everything is working before I cut a new release?

**Comment by 3mp3ri0r** [comment]
Of course I'll try it. Wait.

**Comment by 3mp3ri0r** [comment]
Hi @miguelgrinberg, I've tried it and I got no problem with sanic invalid usage, but I got:

> [2018-05-12 01:54:44 +0000] - (sanic.access)[INFO][1:7]: OPTIONS http://localhost:8000/socket.io/?EIO=3&transport=polling&t=MDI3h8H  405 16

Why my frontend apps still uable to access python-socketio? I still get 405 Method not allowed.

**Comment by miguelgrinberg** [comment]
Did you install the master branch for python-engineio, direct from GitHub? This fix has not been officially released yet.

**Comment by 3mp3ri0r** [comment]
Yes I'm using master branch from github by doing:
`pip install git+https://github.com/miguelgrinberg/python-engineio.git`

Any idea?

**Comment by 3mp3ri0r** [comment]
Yay! You've solved the problem, @miguelgrinberg. Thanks. Anyway do you know why socketio transport don't upgraded from polling to websocket when connecting from other domain?

**Comment by 3mp3ri0r** [comment]
I got a gotcha. When I call asyncserver with `cors_allowed_origins` set, socketio-client won't upgrade from polling to websocket. This is the example:
`sio = socketio.AsyncServer(async_mode='sanic', client_manager=mgr, cors_allowed_origins='*:*', logger=True)`

Client will upgrade to websocket from polling when `cors_allowed_origins` unset like this:
`sio = socketio.AsyncServer(async_mode='sanic', client_manager=mgr)`

Thanks for your help @miguelgrinberg.

**Comment by miguelgrinberg** [comment]
Is `*:*` a valid CORS origin specification? I don't think it is, you have to use a single `*` to allow all domains.

**Comment by 3mp3ri0r** [comment]
Yes. I think so. I just search it and some one recomend to do it, but now I know that it was incorrect. 😂

**Comment by miguelgrinberg** [comment]
@3mp3ri0r release 2.1.1 is now in pypi. Enjoy!

**Comment by 3mp3ri0r** [comment]
Hurray! 🎉🎊
Thanks @miguelgrinberg.
