### ISSUE TITLE
Support for Quart

### ISSUE THREAD

**Issue by kondalrao** [miguelgrinberg/python-engineio#74]
I see that sanic and aiohttp is supported.

Could we have a support for Quart (Flash async counterpart) with engineio?

**Comment by miguelgrinberg** [comment]
I don't see why not. Eventually I might look into it myself if nobody does it.

**Comment by a137x** [comment]
Dear @miguelgrinberg any progress on this enhancement? Seems like nobody does it

**Comment by miguelgrinberg** [comment]
No, I have not attempted this myself. Unfortunately at this time I think the number of people who would benefit is rather small, and I don't have a lot of time available.

**Comment by miguelgrinberg** [comment]
Quart is now indirectly supported via the new ASGI server support.
