### ISSUE TITLE
Support for multiple handlers for a specific event

### ISSUE THREAD

**Issue by PierrePaul** [miguelgrinberg/python-engineio#77]
Any idea of how hard/feasible it would be to support multiple handlers for the same event?
```python
@socketio.on('message')
def get_message_1():
    print("hi from message 1")

@socketio.on('message')
def get_message_2():
   print("hi from message 2")
```
Right now, only `hi from message 2` is shown.

Or maybe it's already possible but with another syntax?
Thanks for your time!

**Comment by PierrePaul** [comment]
Maybe more details for my specific use case. I have multiple blueprints that needs to listen to the same event, but will do specific magic for their blueprint.

**Comment by miguelgrinberg** [comment]
The concept of blueprints does not apply to Socket.IO. Consider that this is a permanent connection, where the client or the server can send any events to the other party. When the client sends an event, all it does is send an event name and optionally some arguments, that's it. There is no context to decide if this should be handled by the first or the second handler of a given event name.

If instead, you want to have two separate connections, and you want to handle some event name in both connections with different handlers, then that can be done with namespaces. Just use different namespaces for your two connections:

```python
@socketio.on('message', namespace='/first')
def get_message_1():
    print("hi from message 1")

@socketio.on('message', namespace='/second')
def get_message_2():
   print("hi from message 2")
```

The client will have to make two connections and then depending on the connection it emits the event, the correct handler will run. Hope this helps!

**Comment by miguelgrinberg** [comment]
> It would be neat if we could register multiple handlers and have each one called sequentially, by order or insertion I guess.

This is very difficult to implement reliably in practice. Order of insertion is really undetermined when you use decorators to register your handlers, it depends on your imports, and it can change as you make changes to the code.

This is also a strange concept for other Socket.IO implementations or for the protocol itself.

**Comment by PierrePaul** [comment]
> Order of insertion is really undetermined when you use decorators to register your handlers
> This is also a strange concept for other Socket.IO implementations or for the protocol itself.

Totally agree with you. Thanks for your time and your input.
