### ISSUE TITLE
Tornado support

### ISSUE THREAD

**Issue by jasongrout** [miguelgrinberg/python-engineio#8]
I'm hoping to use engineio and Primus to implement websocket+fallback for the Jupyter notebook, which uses Tornado to serve web requests.  Have you looked into supporting Tornado?

**Comment by miguelgrinberg** [comment]
@jasongrout I have not investigated any other frameworks besides Flask, which I know well. This package and python-socketio are both framework agnostic, so it should be possible to integrate with any framework, or also use directly without an integration layer if necessary. Currently the asynchronous operations are handled with regular Python threads, or with eventlet or gevent. Other async frameworks can be added.

Unfortunately I don't think I will have time in the near future to take on another wrapper besides the Flask one. But if you would like to give it a try I will be more than happy to help.

**Comment by jasongrout** [comment]
Thanks!  We're still evaluating using primus or just using sockjs directly.  If we use Primus, I'll see about submitting a PR.
