### ISSUE TITLE
Some times, it will cased endless looping by a closed socket but not removed from sockets.

### ISSUE THREAD

**Issue by wanghaihan** [miguelgrinberg/python-engineio#81]
I don't know why there is always a socket with closed=True and closing= True in `self.sockets.copy().values() ` sometimes. But it did happen on occasion.
And it will make CPU keep 100% due to this endless loop
`                for s in self.sockets.copy().values():
                    if s.closed:
                        continue`
So if there missing some sleep and counter to make sure remove a socket with long time closing statues.

https://github.com/miguelgrinberg/python-engineio/blob/2f5cd48f0f574c4cabd63f0b46dd652ff93ffc89/engineio/server.py#L527

**Comment by miguelgrinberg** [comment]
Oh, I see. Thanks, I'll fix that.

**Comment by miguelgrinberg** [comment]
Fixed in v2.3.2.
