### ISSUE TITLE
_server_task puzzlement

### ISSUE THREAD

**Issue by bhyde** [miguelgrinberg/python-engineio#82]
I have some questions about [_server_task](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/server.py#L513).

My attention was drawn to this routine because I'm I have a flask based websockets service that is occasionally  misbehaving.  The code in my client browsers starts announcing that it's not working.  In some cases the server becomes very cpu intensive while at the sametime it's pss footprint becomes quite minimal.

So I attach to it with pyrasite and grab a backtrace.  I have about 20 of those from 3 incidents; and in all cases the backtrace points to _server_task either the ```for s in self.sockets.copy().values():``` or the ```if len(self.sockets) == 0:``` line.

Pyrasite-shell let's me see that the sockets table has a len of 200-250 entries; the vast majority of those are closed.

Ok, so my questions.

I think the sleep_interval computation is in error.  It divides by the entire length of the sockets; but the loop only sleeps for those entries that are not closed.   The loop while loop wants to run one cycle ever ping_interval, but it's going to run faster than that depending on how many are closed.

I've failed to guess what the intent of  the copy here is: ```self.sockets.copy().values()```.  Maybe to reduce the risk of modifications by another thread.  It doesn't eliminate the risk, does it? 
```
    def _service_task(self):  # pragma: no cover
        """Monitor connected clients and clean up those that time out."""
        while True:
            if len(self.sockets) == 0:
                # nothing to do
                self.sleep(self.ping_timeout)
                continue

            # go through the entire client list in a ping interval cycle
            sleep_interval = self.ping_timeout / len(self.sockets)

            try:
                # iterate over the current clients
                for s in self.sockets.copy().values():
                        if s.closed:
                            continue
                    s.check_ping_timeout()
                    self.sleep(sleep_interval)
            except:
                # an unexpected exception has occurred, log it and continue
                self.logger.exception('service task exception')
```

Any guess as to why my backtrace sampling hasn't ever caught it in the sleep would be most welcome.

So far my somewhat shallow efforts to puzzle out what removes entries from sockets has yet to bear fruit.

**Comment by miguelgrinberg** [comment]
I think you are using an older version of the python-engineio package. I have fixed the problem with the sleep in the loop. The reason the socket list is copied is that the `check_ping_timeout()` function will remove any closed sockets from the list. You can't iterate over a list that is changing.

**Comment by bhyde** [comment]
My apologies for not noticing I was out of sync.  That does look like to fix my troubles; and I've deployed it.  Finger's crossed.
