### ISSUE TITLE
Hooking Into ASGI Lifespan Events

### ISSUE THREAD

**Issue by rawberg** [miguelgrinberg/python-engineio#86]
Trying to figure out how to hook into ASGI 'lifespan.startup' and 'lifespan.shutdown' events in order to setup a DB connection. After reading the [lifespan](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/async_drivers/asgi.py#L84) method and the [spec](https://asgi.readthedocs.io/en/latest/specs/lifespan.html) still not quite sure how to run code when those events fire.

thought it might be `@eio.on("lifespan.startup")` or `@eio.on("lifespan.startup.complete")` but that didn't seem to work. still new to asgi, do these need to be placed on the asgi app that comes back from calling `ASGIApp()`? Currently using uvicorn.

**Comment by miguelgrinberg** [comment]
This works in a similar way to WSGI, you can wrap the ASGI app that you have from this package with your own, and then you can override or pass-thru any of the ASGI events. Alternatively, you can also create a subclass of `ASGIApp` and override the `lifespan()` method, but the first approach seems cleaner to me.

**Comment by miguelgrinberg** [comment]
The Socket.IO server is not a general purpose ASGI framework, so it does not provide entry points to ASGI events. ASGI is just one of several web server protocols that I support.

The server listens for the lifespan events, but not to pass them on to you, it just uses them to perform its own initialization. As I said above, ASGI apps are composable and chainable, so you can write a simple ASGI app that does what you need to do on the lifespan events, and then passes control to the ASGI app generated by the Socket.IO server.

**Comment by rawberg** [comment]
Thanks for the the guidance and these libraries!
