### ISSUE TITLE
some questions regarding the connection handling and graceful shutdown

### ISSUE THREAD

**Issue by imcom** [miguelgrinberg/python-engineio#94]
Hi @miguelgrinberg 

Just some general questions. I am using python-socketio , backed by engineio. The scenario I want to use the socketio is to establish monitoring on an LVS (IPVS) LB cluster. Where we have two tiers LB, the first tier uses BGP to discover and dynamically route traffic to the second tier LB which is LVS. SocketIO turns out to be a good choice to detect routing change / BGP flapping. Because it will cause RSTs due to unexpected routing changes. However, I found it is a bit difficult to quit the entire process immediately once there are events like "disconnect" or "timeout" on emit. The process always gets stuck somewhere trying to send some data to the server, while the network might have been dropping packets (due to next-hop missing etc..)

So .. any advice on how to leverage socketio or engineio directly to act as a mean to detection routing changes and fail quickly on disconnect/transmission timeout?

Thanks in advance.

The client code is pretty simple

```python
# standard Python
sio = socketio.Client(reconnection=False, logger=True, engineio_logger=True)


WS_ADDR = os.getenv("WS_ADDR", "http://server:8080")


class Servant(socketio.ClientNamespace):
    def __init__(self, ws_addr, interval):
        super(Servant, self).__init__()
        self.ws_addr = ws_addr
        self.interval = interval

    def on_connect(self):
        log.info("connected to the server, transport: %s", sio.transport())

    def on_disconnect(self):
        log.info("disconnected from the server")

    def on_heartbeat(self, data):
        log.info("received from server: %s", data)

    def __enter__(self):
        return self

    def __exit__(self, type, value, tb):
        return

    def serve(self):
        while True:
            # do something here
            try:
                sio.emit("heartbeat", data="hello world",
                         wait=True, timeout=self.interval)
                time.sleep(self.interval)
            except Exception:
                break


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    try:
        with Servant(WS_ADDR, 3) as s:
            sio.register_namespace(s)
            sio.connect(WS_ADDR, transports=["websocket"])
            s.serve()
    except KeyboardInterrupt:
        sys.exit(0)

    sys.exit(1)
```

My requirement is rather straightforward also, I just need it to quit on disconnect/timeout quickly. I use docker to run the client, so if it quits with non-zero exit code, docker will take care of the retry for me.

**Comment by miguelgrinberg** [comment]
Run your client in this way:

    sio.connect(...)
    sio.wait()

Then when the connection breaks the `wait()` call will return and you can exit your process. You will need to do your heartbeats in a separate thread so that you can use the blocking `wait()` call.
